/* Small library references, never copies of full-resolution texture pixels. */
const favoritesState={lists:{paint:[],p3d:[]},query:'',filter:'all'};
try{const saved=JSON.parse(localStorage.getItem('gs.favorites')||'{}');for(const key of ['paint','p3d'])if(Array.isArray(saved[key]))favoritesState.lists[key]=saved[key].filter(r=>r&&['brush','tool','mat','smart','smask','tex'].includes(r.kind)&&typeof r.name==='string'&&(r.kind==='brush'?typeof r.set==='string':typeof r.id==='string')).slice(0,200);}catch(e){}
const favoritesScope=()=>ui.mode==='p3d'?'p3d':'paint';
function favoritesSave(){try{localStorage.setItem('gs.favorites',JSON.stringify(favoritesState.lists));}catch(e){toast('Could not save Favorites on this computer.');}}
function favoritesRef(kind,rec){if(kind==='tool')return {kind,id:rec.id,name:rec.name};if(kind==='brush'){const set=library.find(s=>s.presets.includes(rec));return set?{kind,set:set.id,name:rec.name,index:set.presets.indexOf(rec)}:null;}if(!['mat','smart','smask','tex'].includes(kind))return null;return {kind,id:rec.id,name:rec.name,textureKind:kind==='tex'?rec.kind:undefined};}
function favoritesKey(ref){return ref.kind+':'+(ref.set||ref.textureKind||'')+':'+(ref.id||ref.name);}
function favoritesResolve(ref){if(ref.kind==='tool'){const id=ref.id.split(':')[0],cmd=KB_EXTRA.find(c=>c[0]==='tool:'+id);return cmd||['burn','bucket','gbucket'].includes(id)?{id:ref.id,name:ref.name}:null;}if(ref.kind==='brush'){const set=library.find(s=>s.id===ref.set);return set?.presets.find(p=>p.name===ref.name)||null;}if(ref.kind==='tex')return txItems().find(r=>r.id===ref.id&&r.kind===ref.textureKind)||null;
  const choices=ref.kind==='smart'?matLib.list.filter(r=>r.kind==='smart').concat(smBuiltins()):ref.kind==='smask'?matLib.list.filter(r=>r.kind==='smask').concat(smaskBuiltins()):matLib.list.filter(r=>!r.kind||r.kind==='material').concat(matBuiltins(),gmRecs);return choices.find(r=>r.id===ref.id)||null;}
function favoritesAdd(kind,rec){const ref=favoritesRef(kind,rec);if(!ref){toast('Drag a tool, brush, texture, material or smart mask here.');return;}const list=favoritesState.lists[favoritesScope()];if(list.some(r=>favoritesKey(r)===favoritesKey(ref))){toast('Already in Favorites.');return;}if(list.length>=200){toast('This collection is full. Remove a favorite first.');return;}list.push(ref);favoritesSave();renderFavorites();toast('Added “'+rec.name+'” to '+(favoritesScope()==='p3d'?'3D Paint':'2D')+' Favorites.');}
function favoritesRemove(ref){favoritesState.lists[favoritesScope()]=favoritesState.lists[favoritesScope()].filter(r=>favoritesKey(r)!==favoritesKey(ref));favoritesSave();renderFavorites();}
function favoritesUse(ref,rec){if(!rec){toast('This favorite is unavailable. Reimport its original library item or remove the favorite.');return;}if(ref.kind==='tool'){const [tool,mode]=rec.id.split(':');if(tool==='heal'&&['spot','source'].includes(mode)){heal.mode=mode;healSave();}return setTool(tool);}if(ref.kind==='brush')return applyPreset(rec);if(ref.kind==='tex')return txToLayer(rec);if(ui.mode!=='p3d'){toast('Materials and smart masks are used in 3D Paint.');return;}matPick(ref.kind,rec);showPanel('mats');toast('Selected “'+rec.name+'”. Use the material controls or drag it onto a layer.');}
const favoritesSearch=el('input',{type:'search','aria-label':'Search Favorites',placeholder:'Search favorites',oninput:()=>{favoritesState.query=favoritesSearch.value;renderFavorites();}});
const favoritesFilter=el('select',{'aria-label':'Favorite type',onchange:()=>{favoritesState.filter=favoritesFilter.value;renderFavorites();}},...[['all','All types'],['tool','Tools'],['brush','Brushes'],['tex','Textures'],['mat','Materials'],['smart','Smart materials'],['smask','Smart masks']].map(([value,text])=>el('option',{value,text})));
const favoritesBody=el('div',{id:'favoritesBody'}),favoritesContext=el('div',{class:'sub',id:'favoritesContext'});
const favoritesSection=el('section',{class:'sec',id:'favoritesSec','aria-labelledby':'hFavorites'},el('div',{class:'sec-h',id:'hFavorites',text:'Favorites'}),favoritesContext,el('div',{class:'favorites-controls'},favoritesSearch,favoritesFilter),favoritesBody);
document.body.append(favoritesSection);
function renderFavorites(){favoritesContext.textContent=favoritesScope()==='p3d'?'3D Paint favorites':'2D canvas favorites';txForget(favoritesBody);favoritesBody.replaceChildren();const list=favoritesState.lists[favoritesScope()],query=favoritesState.query.toLowerCase(),shown=list.filter(r=>(favoritesState.filter==='all'||r.kind===favoritesState.filter)&&r.name.toLowerCase().includes(query));
  const grid=el('div',{class:'matgrid favorites-grid'});for(const ref of shown){const rec=favoritesResolve(ref),wrap=el('div',{class:'favorite-wrap'}),tile=el('button',{class:'mattile favorite-tile',title:ref.name,'aria-label':ref.name,onclick:()=>favoritesUse(ref,rec)});let preview;
    if(!rec)preview=el('div',{class:'favorite-missing',text:'Unavailable'});
    else if(ref.kind==='tool'){const tool=rec.id.split(':')[0],source=document.querySelector('#tools .tool[data-tool="'+tool+'"] svg');preview=source?source.cloneNode(true):el('span',{class:'favorite-tool-fallback',text:ref.name.slice(0,1)});preview.classList.add('favorite-tool-icon');}
    else if(ref.kind==='brush')preview=tileCanvas(rec);
    else if(ref.kind==='tex'){preview=el('img',{alt:'',width:72,height:72,draggable:'false'});preview._tx=rec;txObserve(preview);}
    else if(rec.thumb)preview=el('img',{src:rec.thumb,alt:'',width:72,height:72,draggable:'false'});
    else if(ref.kind==='smart')preview=smPreviewEl(rec,72);
    else if(ref.kind==='smask')preview=smaskPreviewEl(rec,72);
    else preview=rec.fill?matPreviewEl(()=>rec.fill,()=>({}),72).el:el('div',{class:'favorite-missing',text:'Material'});
    if(rec)tile._libDrag=[ref.kind,rec];tile.append(preview,el('span',{text:ref.name}),el('small',{text:{tool:'Tool',brush:'Brush',tex:'Texture',mat:'Material',smart:'Smart material',smask:'Smart mask'}[ref.kind]}));wrap.append(tile,el('button',{class:'favorite-remove',text:'×','aria-label':'Remove '+ref.name+' from Favorites',title:'Remove favorite',onclick:()=>favoritesRemove(ref)}));grid.append(wrap);}
  favoritesBody.append(grid,el('p',{class:'note',text:!list.length?'Drag toolbar tools, brushes, textures, materials or smart masks here. This collection is separate from '+(favoritesScope()==='p3d'?'2D canvas':'3D Paint')+' Favorites.':!shown.length?'No matching favorites.':'Drag favorites onto layers or click to select/use them. Removing a favorite keeps the original library item.'}));}
MENUS.Window.push('-',['Favorites','pn_favorites']);actions.pn_favorites=()=>{showPanel('favorites');renderFavorites();};
renderFavorites();

for(const fn of ['renderLibrary','renderMats']){const original=fn==='renderLibrary'?renderLibrary:renderMats;const wrapped=function(...args){const result=original(...args);if(favoritesSection.isConnected&&favoritesSection.getClientRects().length)renderFavorites();return result;};if(fn==='renderLibrary')renderLibrary=wrapped;else renderMats=wrapped;}
