/* ================= Menus ================= */
const MENUS={
  File:[['New document…','new','Ctrl+Alt+N'],['Open… (Gouache, PSD, PNG, TGA, DDS, TIFF, JPG)','open','Ctrl+O'],['All recent files…','recent'],['Welcome screen and examples…','welcome'],['Place image as layer…','place'],['Turn canvas into a texture…','toTexture'],'-',['Save','save','Ctrl+S'],['Save as…','saveAs','Ctrl+Shift+S'],['Export as PSD…','savePsdAs'],['Export… (PNG, TGA, DDS, TIFF, EXR, JPG)','export','Ctrl+Shift+E'],['Export textures for a game engine…','expTex'],['Import a model… (OBJ, glTF, FBX)','impModel'],['Bake mesh maps…','p3BakeMenu'],['Send to 3D Paint (as a layer)','sendP3'],'-',['Import brushes (.abr)…','importAbr'],'-',['Frames from a sprite sheet…','impSheet'],['Frames from an image sequence…','impSeq'],['Frames from a GIF…','impGif'],['Export sprite sheet / flipbook…','expSheet'],'-',['Check for updates…','checkUpdates']],
  Edit:[['Undo','undo','Ctrl+Z'],['Redo','redo','Ctrl+Shift+Z'],'-',['Cut','cut','Ctrl+X'],['Copy','copy','Ctrl+C'],['Copy merged','copyMerged','Ctrl+Shift+C'],['Paste','paste','Ctrl+V'],'-',['Fill with foreground','fill','Alt+Del'],['Clear','clear','Del'],'-',['Free transform','freeTransform','Ctrl+T'],'-',['Make brush tip…','makeTip'],'-',['Keyboard shortcuts…','keys'],['Preferences…','prefs','Ctrl+K']],
  Image:[['Canvas size…','canvasSize'],['Image size…','imageSize'],['Crop to selection','cropSel'],'-',['8 bits per channel','depth8'],['16 bits per channel (half float)','depth16']],
  Maps:[['Document maps…','maps'],'-',['Convert tab…','convertTab'],['Height from base colour…','cvHeight'],['Normal from base colour…','cvNormal'],['Roughness from base colour…','cvRough'],'-',
    ['Ambient occlusion from height…','cvAO'],['Curvature from height…','cvCurv'],'-',['Curvature from normal…','cvCurvN'],['Ambient occlusion from normal…','cvAON'],['Height from normal…','cvHfN'],['Flip normal green (DirectX ↔ OpenGL)','flipG'],'-',['Bake from high poly…','bake']],
  Layer:[['New','sub',[['Layer','addLayer','Ctrl+Shift+N'],['Group','newGroup'],['Fill layer…','newFill'],['Filter layer…','newFx']]],['Duplicate','dupLayer','Ctrl+J'],['Delete','delLayer','Del'],'-',
    ['Layer style…','layerStyle'],['Array…','arrayTool'],['Edit filter layer…','editFx'],'-',
    ['Layer mask','sub',[['Reveal all','addMask'],['Hide all','addMaskHide'],['Apply mask','applyMask'],['Delete mask','deleteMask']]],'-',
    ['Group selected','group','Ctrl+G'],['Ungroup','ungroup','Ctrl+Shift+G'],'-',
    ['Rasterize text, shape or fill','rasterize'],['Make brush tip from layer','tipFromLayer'],'-',
    ['Merge down / selected','merge','Ctrl+E'],['Merge group','mergeGroup'],['Merge visible','mergeVisible'],['Flatten image','flatten']],
  Select:[['All','selAll','Ctrl+A'],['Deselect','deselect','Ctrl+D'],['Reselect','reselect','Ctrl+Shift+D'],['Invert','selInvert','Ctrl+Shift+I'],'-',
    ['Feather…','selFeather'],['Expand…','selExpand'],['Contract…','selContract'],['Smooth…','selSmooth'],'-',['Select layer pixels','selLayer','Ctrl+click thumbnail'],['Load selection…','selLoad'],'-',['Quick mask','quickMask','Q']],
  Adjust:[['Color adjustments…','adjust','Ctrl+U'],['Levels…','levels','Ctrl+L'],['Curves…','curves','Ctrl+M'],['Hue / Saturation…','hueSat'],['Gradient map…','gradMap'],'-',
    ['Invert','invert','Ctrl+I'],['Desaturate','desat','Ctrl+Shift+U'],['Threshold…','threshold'],['Posterize…','posterize'],['Quantize…','quantize']],
  Filter:[['Filter Gallery…','gallery','Ctrl+Shift+F'],['Embroidery patch…','embroidery'],['Mesh maps from material…','matConvert'],'-',
    ['Blur','sub',[['Gaussian blur…','blur'],['Box blur…','boxBlur'],['Radial blur…','radialBlur'],['Lens blur…','lensBlur'],['Surface blur…','surfBlur'],['Motion blur…','motionBlur'],['Drift blur…','driftBlur'],['Slope blur…','slopeBlur']]],
    ['Sharpen','sub',[['Sharpen…','sharpen'],['High pass…','highPass']]],
    ['Distort','sub',[['Warp…','warp'],['Distort…','distort'],['Glass…','glass'],['Acid…','acid']]],
    ['Paint and sketch','sub',[['Oil paint…','oilPaint'],['Painterly…','painterly'],['Kuwahara…','kuwahara'],['Watercolour…','watercolour'],['Charcoal…','charcoal'],['Cutout…','cutout'],['Mosaic…','mosaic']]],
    ['Photo looks','sub',[['Soft focus…','softFocus'],['Cinematic mono…','cineMono'],['Anaglyph…','anaglyph']]],
    ['Print','sub',[['Halftone…','halftone'],['Engraving…','engraving'],['Riso print…','riso'],['B&W print…','bwPrint'],['Pixel / bitmap…','pixelBitmap']]],
    ['Edges and relief','sub',[['Emboss…','emboss'],['Find edges…','edges'],['Edge wear…','edgeWear']]],
    ['Noise and render','sub',[['Add noise…','noise'],['Render clouds…','clouds'],['Render cells…','cells']]],
    ['Tiling','sub',[['Offset…','offset'],['Tile…','tile_fx'],['Make seamless…','seamless']]]],
  View:[['Fit on screen','fit','Ctrl+0'],['Actual pixels','actual','Ctrl+1'],['Tile mode','tile','Shift+T'],['3D view','view3d','F3'],'-',['Cage tool','cageTool','K'],['Flat cage view','cageFlat','F'],['Symmetry: left–right','symX','Shift+X'],'-',['Shortcut hints','hints'],['Performance monitor','perf']],
  Window:[['Workspace: Painting','ws_painting'],['Workspace: Texturing','ws_texturing'],['Workspace: 3D Paint','ws_paint3d'],['Workspace: Minimal','ws_minimal'],['Save workspace…','wsSave'],['Reset workspace','wsReset'],['Lock panels','wsLock'],'-',
    ['Color','pn_color'],['Brushes','pn_brushes'],['Tool settings','pn_tool'],['Maps','pn_maps'],['Layers','pn_layers'],['Channels','pn_chan'],'-',['Options bar','optBarToggle'],['Toolbar: two columns','tbCols'],['Toolbar on the right','tbSide']],
  Help:[] /* filled by ui/help.js */
};
const actions={impModel:()=>importModel().then(()=>{if(ui.mode==='p3d'){p3.imported=v3.imported;buildP3Panel();}}),p3BakeMenu:()=>dlgP3Bake(),new:dlgNew,open:()=>pickFile('open'),toTexture:()=>dlgToTexture(),place:()=>pickFile('place'),export:dlgExport,savePsd:()=>withPaintDocAsync(()=>savePSD(false)),savePsdAs:()=>withPaintDocAsync(savePSDAs),save:()=>ui.mode==='p3d'?saveP3Project(false):withPaintDocAsync(()=>saveDoc(false)),saveAs:()=>ui.mode==='p3d'?saveP3Project(true):withPaintDocAsync(()=>saveDoc(true)),recent:()=>platform.isDesktop?dlgRecent():toast('Recent files are available in the desktop app.'),importAbr:()=>pickFile('abr'),checkUpdates:()=>checkForUpdates(true),tipFromLayer,undo,redo,fill:fillLayer,clear:clearLayer,
  canvasSize:dlgCanvasSize,matConvert:()=>dlgMatConvert(),layerStyle:()=>dlgLayerStyle(),arrayTool:()=>setTool('array'),bake:()=>setMode('bake'),convertTab:()=>setMode('convert'),view3d:()=>toggle3D(),newFx:cmdNewFxLayer,embroidery:()=>dlgEmbroidery(),sendP3:()=>sendToP3(),newFill:()=>cmdNewFillLayer(),editFx:editActiveFx,levels:()=>fxMenu('levels'),curves:()=>fxMenu('curves'),hueSat:()=>fxMenu('hueSat'),gradMap:()=>fxMenu('gradMap'),desat:()=>fxMenu('desat'),threshold:()=>fxMenu('threshold'),quantize:()=>fxMenu('quantize'),surfBlur:()=>fxMenu('surfBlur'),motionBlur:()=>fxMenu('motionBlur'),highPass:()=>fxMenu('highPass'),oilPaint:()=>fxMenu('oilPaint'),painterly:()=>fxMenu('painterly'),cutout:()=>fxMenu('cutout'),mosaic:()=>fxMenu('mosaic'),emboss:()=>fxMenu('emboss'),edges:()=>fxMenu('edges'),edgeWear:()=>fxMenu('edgeWear'),noise:()=>fxMenu('noise'),clouds:()=>fxMenu('clouds'),cells:()=>fxMenu('cells'),offset:()=>fxMenu('offset'),seamless:()=>fxMenu('seamless'),tile_fx:()=>fxMenu('tile'),boxBlur:()=>fxMenu('boxBlur'),radialBlur:()=>fxMenu('radialBlur'),lensBlur:()=>fxMenu('lensBlur'),cvHeight:()=>cvOpen('base','height'),cvNormal:()=>cvOpen('base','normal'),cvRough:()=>cvOpen('base','rough'),cvAO:()=>cvOpen('height','ao'),cvCurv:()=>cvOpen('height','curv'),cvHfN:()=>cvOpen('normal','height'),cvCurvN:()=>cvOpen('normal','curv'),cvAON:()=>cvOpen('normal','ao'),flipG:flipNormalGreen,perf:togglePerf,expTex:dlgExportTextures,maps:dlgMaps,imageSize:dlgImageSize,depth8:()=>setDepth(8),depth16:()=>setDepth(16),addLayer:()=>cmdAddLayer(),newGroup:cmdNewGroup,group:cmdGroup,ungroup:cmdUngroup,dupLayer:cmdDuplicate,merge:cmdMerge,mergeGroup:()=>{if(doc.active&&doc.active.type==='group')cmdMergeGroup();else toast('Select a group to merge.');},mergeVisible:cmdMergeVisible,rasterize:()=>{const L=activeText();if(L){rasterizeText(L);toast('Text converted to pixels.');}else toast('Select a text layer first.');},addMask:()=>cmdAddMask(1),addMaskHide:()=>cmdAddMask(0),applyMask:()=>{if(isLayer(doc.active)&&doc.active.mask)cmdApplyMask();else toast('Select a layer that has a mask.');},deleteMask:()=>{if(doc.active&&doc.active.mask)cmdDeleteMask();else toast('The selection has no mask.');},flatten:cmdFlatten,delLayer:cmdDelete,
  cut:()=>{if(cutSel())writeClipMarker();},copy:()=>{if(copySel(false))writeClipMarker();},copyMerged:()=>{if(copySel(true))writeClipMarker();},paste:()=>{const mt=ui.mode==='paint'&&clip?maskEditTarget():null;if(mt)pasteClipIntoMask(mt);else pasteClip();},
  prefs:dlgPrefs,impSheet:importSheet,impSeq:importSequence,impGif:importGif,expSheet:()=>{if(!doc.anim){if(setMode('anim',true))toast('Animation mode: paint your frames, then export.');return;}dlgExportSheet();},freeTransform,cropSel:cropToSelection,selAll:selectAll,deselect,reselect,selInvert:invertSel,selFeather:dlgFeather,selExpand:dlgExpand,selContract:dlgContract,selSmooth:dlgSmooth,selLayer:()=>selectLayerPixels(null,'new'),selLoad:dlgLoadSel,quickMask:toggleQuickMask,
  adjust:()=>fxMenu('colorAdj'),invert,posterize:()=>fxMenu('posterize'),blur:()=>fxMenu('blur'),sharpen:()=>fxMenu('sharpen'),fit,actual,tile:toggleTile};
/* the Brush tab's sketch is not a document: saving it would be a surprise */
for(const k of ['save','saveAs','savePsdAs','export','expTex']){const f=actions[k];actions[k]=(...a)=>{if(ui.mode==='brush'){toast('The Brush tab makes brushes: press Make brush. Switch to Paint to save your document.');return;}return f(...a);};}
Object.assign(actions,{gallery:()=>dlgGallery(),warp:()=>fxMenu('warp'),slopeBlur:()=>fxMenu('slopeBlur'),distort:()=>fxMenu('distort'),kuwahara:()=>fxMenu('kuwahara'),watercolour:()=>fxMenu('watercolour'),charcoal:()=>fxMenu('charcoal'),acid:()=>fxMenu('acid'),softFocus:()=>fxMenu('softFocus'),cineMono:()=>fxMenu('cineMono'),anaglyph:()=>fxMenu('anaglyph'),halftone:()=>fxMenu('halftone'),engraving:()=>fxMenu('engraving'),riso:()=>fxMenu('riso'),bwPrint:()=>fxMenu('bwPrint'),pixelBitmap:()=>fxMenu('pixelBitmap'),glass:()=>fxMenu('glass'),driftBlur:()=>fxMenu('driftBlur'),ws_painting:()=>setWorkspace('painting'),ws_texturing:()=>setWorkspace('texturing'),ws_paint3d:()=>setWorkspace('paint3d'),ws_minimal:()=>setWorkspace('minimal'),wsSave:()=>saveWorkspaceAs(),wsReset:()=>resetWorkspace(),wsLock:()=>toggleLockPanels(),
  pn_color:()=>togglePanel('color'),pn_brushes:()=>togglePanel('brushes'),pn_tool:()=>togglePanel('tool'),pn_maps:()=>togglePanel('maps'),pn_layers:()=>togglePanel('layers'),pn_chan:()=>togglePanel('chan'),
  optBarToggle:()=>{dk.L.opt=!dk.L.opt;dkRender();dkSave();},tbCols:()=>dkToolbar({cols:dk.L.tb.cols===2?1:2}),tbSide:()=>dkToolbar({side:dk.L.tb.side==='right'?'left':'right'})});
Object.assign(actions,{makeTip:()=>dlgMakeTip(),keys:()=>dlgKeys(),hints:()=>toggleHints(),cageTool:()=>{if(ui.cageFlat)cageFlatOff();setTool('cage');},cageFlat:()=>toggleCageFlat(),symX:()=>symToggleX()});
const LAYER_ONLY=['addLayer','newGroup','group','ungroup','dupLayer','delLayer','addMask','addMaskHide','applyMask','deleteMask','merge','mergeGroup','mergeVisible','flatten','rasterize','place','tipFromLayer','selLayer'];
const checked={ws_painting:()=>dk.ws==='painting',ws_texturing:()=>dk.ws==='texturing',ws_paint3d:()=>dk.ws==='paint3d',ws_minimal:()=>dk.ws==='minimal',wsLock:()=>dk.lock,pn_color:()=>panelShown('color'),pn_brushes:()=>panelShown('brushes'),pn_tool:()=>panelShown('tool'),pn_maps:()=>panelShown('maps'),pn_layers:()=>panelShown('layers'),pn_chan:()=>panelShown('chan'),optBarToggle:()=>dk.L&&dk.L.opt,tbCols:()=>dk.L&&dk.L.tb.cols===2,tbSide:()=>dk.L&&dk.L.tb.side==='right',hints:()=>!prefs.hideHints,view3d:()=>v3.on,perf:()=>perf.on,depth8:()=>doc.depth===8,depth16:()=>doc.depth===16,tile:()=>doc.wrap,quickMask:()=>sel.quick};
const pop=$('#menuPop');let openName=null;
/* (0.31) Layer is a menu of its own again, like Photoshop; Maps lives at the end of the Image menu */
MENUS.Image.push('-',['Maps','sub',MENUS.Maps]);delete MENUS.Maps;
const menuBtns={};for(const name in MENUS){const b=el('button',{text:name,'aria-haspopup':'true','aria-expanded':'false'});b.addEventListener('click',()=>openName===name?closeMenu():openMenu(name));b.addEventListener('mouseenter',()=>{if(openName&&openName!==name)openMenu(name);});menuBtns[name]=b;$('#menus').append(b);}
/* a menu entry; ['Name','sub',[entries]] opens a fly-out to the right */
const flyEl=el('div',{id:'menuSub',role:'menu',hidden:true});document.body.append(flyEl);
function flyHide(){flyEl.hidden=true;}
function flyOpen(btn,items){const r=btn.getBoundingClientRect();flyEl.replaceChildren(...items);flyEl.hidden=false;
  const left=r.right+2+flyEl.offsetWidth>window.innerWidth-6?Math.max(4,r.left-flyEl.offsetWidth-2):r.right+2;
  flyEl.style.left=left+'px';flyEl.style.top=Math.max(4,Math.min(r.top-4,window.innerHeight-flyEl.offsetHeight-8))+'px';}
function flyItem(label,items){const b=el('button',{class:'mi hassub',role:'menuitem','aria-haspopup':'true'},el('span'),el('span',{text:label}),el('span',{class:'arr',text:'▸'}));
  b.addEventListener('mouseenter',()=>flyOpen(b,items()));b.addEventListener('click',e=>{e.stopPropagation();flyOpen(b,items());});return b;}
function menuEntry(it){if(it==='-')return el('div',{class:'msep'});
  if(it[1]==='sub')return flyItem(it[0],()=>menuList(it[2]));
  return el('button',{class:'mi',role:'menuitem','data-act':it[1],disabled:it[1]==='depth16'&&!canFloat,onclick:()=>{closeMenu();if(xf&&!xf.move&&it[1]!=='freeTransform')xfCommit();if(ui.mode==='anim'&&LAYER_ONLY.includes(it[1])){toast('Layers are not used in Animation mode. Switch to Paint mode (top right) for layers.');return;}actions[it[1]]();}},el('span',{text:checked[it[1]]&&checked[it[1]]()?'✓':''}),el('span',{text:it[0]}),(()=>{const k=it[2]&&/click/i.test(it[2])?it[2]:kbKeyOf(it[1]);return k?el('kbd',{text:k}):el('span');})());}
/* (0.29) the File menu shows what fits the section you are in: 3D Paint has no PSD or sprite sheets, Paint has no frames, and so on */
const FILE_NOT={paint:['impModel','p3BakeMenu','impSheet','impSeq','impGif','expSheet'],anim:['impModel','p3BakeMenu','sendP3'],p3d:['place','savePsdAs','export','sendP3','importAbr','impSheet','impSeq','impGif','expSheet'],
  bake:['impModel','p3BakeMenu','place','savePsdAs','sendP3','importAbr','impSheet','impSeq','impGif','expSheet','expTex'],convert:['impModel','p3BakeMenu','place','savePsdAs','sendP3','importAbr','impSheet','impSeq','impGif','expSheet','expTex'],
  brush:['impModel','p3BakeMenu','place','savePsdAs','sendP3','expTex','impSheet','impSeq','impGif','expSheet']};
function menuTidy(list){const o=[];for(const it of list){if(it==='-'&&(!o.length||o[o.length-1]==='-'))continue;o.push(it);}while(o.length&&o[o.length-1]==='-')o.pop();return o;}
function menuList(list,name){let l=list.filter(it=>platform.isDesktop||it==='-'||!['recent','checkUpdates'].includes(it[1]));
  if(name==='File'){const no=FILE_NOT[ui.mode]||[];l=menuTidy(l.filter(it=>it==='-'||!no.includes(it[1])));}return l.map(menuEntry);}
function menuFlat(list){const o=[];for(const it of list){if(it==='-')continue;if(it[1]==='sub')o.push(...menuFlat(it[2]));else o.push(it);}return o;}
function openMenu(name){closeMenu();const b=menuBtns[name];
  pop.replaceChildren(...menuList(MENUS[name],name));
  if(name==='File'&&typeof fileMenuExtras==='function')fileMenuExtras(pop);
  const r=b.getBoundingClientRect();pop.hidden=false;pop.style.left=Math.min(r.left,window.innerWidth-pop.offsetWidth-8)+'px';pop.style.top=(r.bottom+3)+'px';b.setAttribute('aria-expanded','true');openName=name;}
function closeMenu(){flyHide();if(!openName)return;pop.hidden=true;menuBtns[openName].setAttribute('aria-expanded','false');openName=null;}
document.addEventListener('pointerdown',e=>{if(openName&&!pop.contains(e.target)&&!flyEl.contains(e.target)&&!$('#menus').contains(e.target))closeMenu();});
pop.addEventListener('keydown',e=>{const items=[...pop.querySelectorAll('.mi:not([disabled])')];const i=items.indexOf(document.activeElement);
  if(e.key==='ArrowDown'){e.preventDefault();(items[i+1]||items[0]).focus();}if(e.key==='ArrowUp'){e.preventDefault();(items[i-1]||items[items.length-1]).focus();}});
