/* ================= Menus ================= */
const MENUS={
  File:[['New document…','new','Ctrl+Alt+N'],['Open… (Gouache, PSD, PNG, TGA, DDS, TIFF, JPG)','open','Ctrl+O'],['Open recent…','recent'],['Place image as layer…','place'],'-',['Save','save','Ctrl+S'],['Save as…','saveAs','Ctrl+Shift+S'],['Export as PSD…','savePsdAs'],['Export… (PNG, TGA, DDS, TIFF, EXR, JPG)','export','Ctrl+Shift+E'],['Export textures for a game engine…','expTex'],'-',['Import brushes (.abr)…','importAbr'],'-',['Frames from a sprite sheet…','impSheet'],['Frames from an image sequence…','impSeq'],['Frames from a GIF…','impGif'],['Export sprite sheet / flipbook…','expSheet'],'-',['Check for updates…','checkUpdates']],
  Edit:[['Undo','undo','Ctrl+Z'],['Redo','redo','Ctrl+Shift+Z'],'-',['Cut','cut','Ctrl+X'],['Copy','copy','Ctrl+C'],['Copy merged','copyMerged','Ctrl+Shift+C'],['Paste','paste','Ctrl+V'],'-',['Fill with foreground','fill','Alt+Del'],['Clear','clear','Del'],'-',['Free transform','freeTransform','Ctrl+T'],'-',['Make brush tip…','makeTip'],'-',['Keyboard shortcuts…','keys'],['Preferences…','prefs','Ctrl+K']],
  Image:[['Canvas size…','canvasSize'],['Image size…','imageSize'],['Crop to selection','cropSel'],'-',['8 bits per channel','depth8'],['16 bits per channel (half float)','depth16']],
  Maps:[['Document maps…','maps'],'-',['Convert tab…','convertTab'],['Height from base colour…','cvHeight'],['Normal from base colour…','cvNormal'],['Roughness from base colour…','cvRough'],'-',
    ['Ambient occlusion from height…','cvAO'],['Curvature from height…','cvCurv'],'-',['Curvature from normal…','cvCurvN'],['Ambient occlusion from normal…','cvAON'],['Height from normal…','cvHfN'],['Flip normal green (DirectX ↔ OpenGL)','flipG'],'-',['Bake from high poly…','bake']],
  Layer:[['New layer','addLayer','Ctrl+Shift+N'],['New filter layer…','newFx'],['Edit filter layer…','editFx'],['New group','newGroup'],['Group selected','group','Ctrl+G'],['Ungroup','ungroup','Ctrl+Shift+G'],['Duplicate','dupLayer','Ctrl+J'],['Delete','delLayer'],'-',
    ['Add mask','addMask'],['Add hide-all mask','addMaskHide'],['Apply mask','applyMask'],['Delete mask','deleteMask'],'-',['Merge down / selected','merge','Ctrl+E'],['Merge group','mergeGroup'],['Merge visible','mergeVisible'],['Flatten image','flatten'],'-',['Rasterize text','rasterize'],['Make brush tip from layer','tipFromLayer']],
  Select:[['All','selAll','Ctrl+A'],['Deselect','deselect','Ctrl+D'],['Reselect','reselect','Ctrl+Shift+D'],['Invert','selInvert','Ctrl+Shift+I'],'-',
    ['Feather…','selFeather'],['Expand…','selExpand'],['Contract…','selContract'],['Smooth…','selSmooth'],'-',['Select layer pixels','selLayer','Ctrl+click thumbnail'],['Load selection…','selLoad'],'-',['Quick mask','quickMask','Q']],
  Adjust:[['Color adjustments…','adjust','Ctrl+U'],['Levels…','levels','Ctrl+L'],['Curves…','curves','Ctrl+M'],['Hue / Saturation…','hueSat'],['Gradient map…','gradMap'],'-',
    ['Invert','invert','Ctrl+I'],['Desaturate','desat','Ctrl+Shift+U'],['Threshold…','threshold'],['Posterize…','posterize'],['Quantize…','quantize']],
  Filter:[['Gaussian blur…','blur'],['Box blur…','boxBlur'],['Radial blur…','radialBlur'],['Lens blur…','lensBlur'],['Surface blur…','surfBlur'],['Motion blur…','motionBlur'],'-',['Sharpen…','sharpen'],['High pass…','highPass'],'-',
    ['Oil paint…','oilPaint'],['Painterly…','painterly'],['Cutout…','cutout'],['Mosaic…','mosaic'],'-',['Emboss…','emboss'],['Find edges…','edges'],['Edge wear…','edgeWear'],'-',
    ['Add noise…','noise'],['Render clouds…','clouds'],['Render cells…','cells'],'-',['Offset…','offset'],['Make seamless…','seamless']],
  View:[['Fit on screen','fit','Ctrl+0'],['Actual pixels','actual','Ctrl+1'],['Tile mode','tile','Shift+T'],['3D view','view3d','F3'],'-',['Cage tool','cageTool','K'],['Flat cage view','cageFlat','F'],['Symmetry: left–right','symX','Shift+X'],'-',['Shortcut hints','hints'],['Performance monitor','perf']]
};
const actions={new:dlgNew,open:()=>pickFile('open'),place:()=>pickFile('place'),export:dlgExport,savePsd:()=>savePSD(false),savePsdAs:savePSDAs,save:()=>saveDoc(false),saveAs:()=>saveDoc(true),recent:()=>platform.isDesktop?dlgRecent():toast('Recent files are available in the desktop app.'),importAbr:()=>pickFile('abr'),checkUpdates:()=>checkForUpdates(true),tipFromLayer,undo,redo,fill:fillLayer,clear:clearLayer,
  canvasSize:dlgCanvasSize,bake:()=>setMode('bake'),convertTab:()=>setMode('convert'),view3d:()=>toggle3D(),newFx:cmdNewFxLayer,editFx:editActiveFx,levels:()=>fxMenu('levels'),curves:()=>fxMenu('curves'),hueSat:()=>fxMenu('hueSat'),gradMap:()=>fxMenu('gradMap'),desat:()=>fxMenu('desat'),threshold:()=>fxMenu('threshold'),quantize:()=>fxMenu('quantize'),surfBlur:()=>fxMenu('surfBlur'),motionBlur:()=>fxMenu('motionBlur'),highPass:()=>fxMenu('highPass'),oilPaint:()=>fxMenu('oilPaint'),painterly:()=>fxMenu('painterly'),cutout:()=>fxMenu('cutout'),mosaic:()=>fxMenu('mosaic'),emboss:()=>fxMenu('emboss'),edges:()=>fxMenu('edges'),edgeWear:()=>fxMenu('edgeWear'),noise:()=>fxMenu('noise'),clouds:()=>fxMenu('clouds'),cells:()=>fxMenu('cells'),offset:()=>fxMenu('offset'),seamless:()=>fxMenu('seamless'),boxBlur:()=>fxMenu('boxBlur'),radialBlur:()=>fxMenu('radialBlur'),lensBlur:()=>fxMenu('lensBlur'),cvHeight:()=>cvOpen('base','height'),cvNormal:()=>cvOpen('base','normal'),cvRough:()=>cvOpen('base','rough'),cvAO:()=>cvOpen('height','ao'),cvCurv:()=>cvOpen('height','curv'),cvHfN:()=>cvOpen('normal','height'),cvCurvN:()=>cvOpen('normal','curv'),cvAON:()=>cvOpen('normal','ao'),flipG:flipNormalGreen,perf:togglePerf,expTex:dlgExportTextures,maps:dlgMaps,imageSize:dlgImageSize,depth8:()=>setDepth(8),depth16:()=>setDepth(16),addLayer:()=>cmdAddLayer(),newGroup:cmdNewGroup,group:cmdGroup,ungroup:cmdUngroup,dupLayer:cmdDuplicate,merge:cmdMerge,mergeGroup:()=>{if(doc.active&&doc.active.type==='group')cmdMergeGroup();else toast('Select a group to merge.');},mergeVisible:cmdMergeVisible,rasterize:()=>{const L=activeText();if(L){rasterizeText(L);toast('Text converted to pixels.');}else toast('Select a text layer first.');},addMask:()=>cmdAddMask(1),addMaskHide:()=>cmdAddMask(0),applyMask:()=>{if(isLayer(doc.active)&&doc.active.mask)cmdApplyMask();else toast('Select a layer that has a mask.');},deleteMask:()=>{if(doc.active&&doc.active.mask)cmdDeleteMask();else toast('The selection has no mask.');},flatten:cmdFlatten,delLayer:cmdDelete,
  cut:()=>{if(cutSel())writeClipMarker();},copy:()=>{if(copySel(false))writeClipMarker();},copyMerged:()=>{if(copySel(true))writeClipMarker();},paste:pasteClip,
  prefs:dlgPrefs,impSheet:importSheet,impSeq:importSequence,impGif:importGif,expSheet:()=>{if(!doc.anim){if(setMode('anim',true))toast('Animation mode: paint your frames, then export.');return;}dlgExportSheet();},freeTransform,cropSel:cropToSelection,selAll:selectAll,deselect,reselect,selInvert:invertSel,selFeather:dlgFeather,selExpand:dlgExpand,selContract:dlgContract,selSmooth:dlgSmooth,selLayer:()=>selectLayerPixels(null,'new'),selLoad:dlgLoadSel,quickMask:toggleQuickMask,
  adjust:()=>fxMenu('colorAdj'),invert,posterize:()=>fxMenu('posterize'),blur:()=>fxMenu('blur'),sharpen:()=>fxMenu('sharpen'),fit,actual,tile:toggleTile};
Object.assign(actions,{makeTip:()=>dlgMakeTip(),keys:()=>dlgKeys(),hints:()=>toggleHints(),cageTool:()=>{if(ui.cageFlat)cageFlatOff();setTool('cage');},cageFlat:()=>toggleCageFlat(),symX:()=>symToggleX()});
const LAYER_ONLY=['addLayer','newGroup','group','ungroup','dupLayer','delLayer','addMask','addMaskHide','applyMask','deleteMask','merge','mergeGroup','mergeVisible','flatten','rasterize','place','tipFromLayer','selLayer'];
const checked={hints:()=>!prefs.hideHints,view3d:()=>v3.on,perf:()=>perf.on,depth8:()=>doc.depth===8,depth16:()=>doc.depth===16,tile:()=>doc.wrap,quickMask:()=>sel.quick};
const pop=$('#menuPop');let openName=null;
const menuBtns={};for(const name in MENUS){const b=el('button',{text:name,'aria-haspopup':'true','aria-expanded':'false'});b.addEventListener('click',()=>openName===name?closeMenu():openMenu(name));b.addEventListener('mouseenter',()=>{if(openName&&openName!==name)openMenu(name);});menuBtns[name]=b;$('#menus').append(b);}
function openMenu(name){closeMenu();const b=menuBtns[name];
  pop.replaceChildren(...MENUS[name].filter(it=>platform.isDesktop||it==='-'||!['recent','checkUpdates'].includes(it[1])).map(it=>it==='-'?el('div',{class:'msep'}):el('button',{class:'mi',role:'menuitem',disabled:it[1]==='depth16'&&!canFloat,onclick:()=>{closeMenu();if(xf&&!xf.move&&it[1]!=='freeTransform')xfCommit();if(ui.mode==='anim'&&LAYER_ONLY.includes(it[1])){toast('Layers are not used in Animation mode. Switch to Paint mode (top right) for layers.');return;}actions[it[1]]();}},el('span',{text:checked[it[1]]&&checked[it[1]]()?'✓':''}),el('span',{text:it[0]}),(()=>{const k=it[2]&&/click/i.test(it[2])?it[2]:kbKeyOf(it[1]);return k?el('kbd',{text:k}):el('span');})())));
  const r=b.getBoundingClientRect();pop.hidden=false;pop.style.left=Math.min(r.left,window.innerWidth-pop.offsetWidth-8)+'px';pop.style.top=(r.bottom+3)+'px';b.setAttribute('aria-expanded','true');openName=name;}
function closeMenu(){if(!openName)return;pop.hidden=true;menuBtns[openName].setAttribute('aria-expanded','false');openName=null;}
document.addEventListener('pointerdown',e=>{if(openName&&!pop.contains(e.target)&&!$('#menus').contains(e.target))closeMenu();});
pop.addEventListener('keydown',e=>{const items=[...pop.querySelectorAll('.mi:not([disabled])')];const i=items.indexOf(document.activeElement);
  if(e.key==='ArrowDown'){e.preventDefault();(items[i+1]||items[0]).focus();}if(e.key==='ArrowUp'){e.preventDefault();(items[i-1]||items[items.length-1]).focus();}});
