/* Project assets are compressed CPU records. Browsing never expands a full-size GPU image.
   Layer tiles borrow their live layer; small previews are only drawn while the shelf is visible. */
const paShelf={filter:'all',query:'',size:'m',tab:'projects',timer:0,thumbs:new WeakMap(),pending:new WeakMap()};
function paOwner(){return ui.mode==='convert'&&tabDocs.paint?tabDocs.paint.doc:doc;}
function paRemember(kind,rec,owner=paOwner(),packed=false){const list=owner.projectAssets||(owner.projectAssets=[]);if(!packed&&!rec.thumb){const im=rec.data?rec:rec.imgs?.base||Object.values(rec.imgs||{})[0];if(im)rec=Object.assign({},rec,{thumb:txThumbPixels(im)});}const job=(async()=>{const asset={kind,rec:packed?rec:await pxDeep(rec,true)};
  const i=list.findIndex(a=>a.kind===kind&&a.rec.id===rec.id);if(i<0)list.push(asset);else list[i]=asset;list._ver=(list._ver||0)+1;paRefresh();return asset;})();return paTrack(list,job);}
function paTrack(list,job){let pending=paShelf.pending.get(list);if(!pending)paShelf.pending.set(list,pending=new Set());pending.add(job);job.then(()=>pending.delete(job),()=>pending.delete(job));return job;}
async function paReady(){const jobs=paShelf.pending.get(doc.projectAssets);while(jobs?.size)await Promise.all([...jobs]);}
/* Include assets in close prompts and recoveries even when the painting pixels did not change. */
function paDocSig(u,D){const last=u.length?u[u.length-1]:null,list=D.projectAssets,v=list?._ver||0;if(!v)return last;const sig=list._sig;if(sig?.last===last&&sig.version===v)return sig;return list._sig={last,version:v};}
function paDocSaved(u,D){const list=D.projectAssets;return (!u.length||u[u.length-1]===D.savedAt)&&(list?._ver||0)===(list?._saved||0);}
function paEncode(put){return (doc.projectAssets||[]).map(a=>{const rec=a.rec,out={kind:a.kind,rec:{id:rec.id,name:rec.name,t:rec.t,thumb:rec.thumb,fill:rec.fill,w:rec.w,h:rec.h,zf:rec.zf}};
  if(rec.z)out.rec.blob=put(rec.z);if(rec.imgs){out.rec.imgs={};for(const [k,im] of Object.entries(rec.imgs))out.rec.imgs[k]={w:im.w,h:im.h,zf:im.zf,blob:put(im.z)};}return out;});}
function paDecode(items,read){return (items||[]).map(a=>{const rec=Object.assign({},a.rec);if(rec.blob){rec.z=read(rec.blob);delete rec.blob;}if(rec.imgs){rec.imgs={};for(const [k,im] of Object.entries(a.rec.imgs))rec.imgs[k]={w:im.w,h:im.h,zf:im.zf,z:read(im.blob)};}return {kind:a.kind,rec};});}
function paVisible(id){const b=$(id);return b&&b.isConnected&&b.getBoundingClientRect().width>0&&b.getBoundingClientRect().height>0;}
function paRefresh(){if(paShelf.timer)return;paShelf.timer=setTimeout(()=>{paShelf.timer=0;if(paVisible('#paBody'))paRender();if(paVisible('#mmBody'))p3MeshLibrary();},120);}
function paEntries(){const out=(doc.projectAssets||[]).map(a=>({kind:a.kind,name:a.rec.name,asset:a}));
  for(const L of paintLayers()){if(L.fx)continue;if(L.fill){out.push({kind:'mat',name:L.name,layer:L});for(const [k,t] of Object.entries(L._fillImg||{}))if(t&&t.tex)out.push({kind:'tex',name:L.name+' · '+(MAP_DEFS[k]?.label||k),layer:L,channel:k,source:t});}
    else for(const k of mapKeysOf(L)){const t=mapT(L,k,true);if(t&&!t.empty&&t.tex)out.push({kind:'tex',name:L.name+(k==='base'?'':' · '+(MAP_DEFS[k]?.label||k)),layer:L,channel:k,source:t});}}
  return out;}
function paPreview(t,ver=0){if(!t||!t.tex)return '';const old=paShelf.thumbs.get(t);if(old&&old.ver===ver)return old.url;const url=txThumbOf(t);paShelf.thumbs.set(t,{ver,url});return url;}
function paThumb(e){if(e.asset){const r=e.asset.rec;return r.thumb||(r.imgs?.base?null:'');}if(e.source)return paPreview(e.source,e.layer.lookVer||0);
  const L=e.layer,t=L._fillImg?.base;if(t)return paPreview(t,L.lookVer||0);const c=L.fill?.maps?.base?.c||[.82,.82,.82];return 'data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="96" height="96"><rect width="96" height="96" fill="rgb('+c.map(v=>Math.round(v*255)).join(',')+')"/></svg>');}
function paRender(){const box=$('#paBody');if(!box||!paVisible('#paBody'))return;box.style.setProperty('--tw',MT_SIZES[paShelf.size]+'px');
  const tabs=seg([['projects','Projects']],paShelf.tab,v=>{paShelf.tab=v;paRender();},'Projects shelf');
  const search=el('input',{type:'search',class:'matsearch',value:paShelf.query,placeholder:'Search project assets','aria-label':'Search project assets'});search.oninput=()=>{paShelf.query=search.value;for(const tile of box.querySelectorAll('[data-asset-name]'))tile.hidden=!tile.dataset.assetName.includes(paShelf.query.toLowerCase());};
  const items=paEntries().filter(e=>paShelf.filter==='all'||e.kind===paShelf.filter),grid=el('div',{class:'matgrid projectgrid'});
  for(const e of items){const tile=el('button',{class:'mattile',title:e.name+' · '+(e.kind==='mat'?'Material':'Texture')+' — click to use; drag onto layers',type:'button'},el('img',{class:'matprev',src:paThumb(e)||'',alt:''}),el('span',{text:e.name}),el('small',{text:e.kind==='mat'?'Material':'Texture'}));tile.dataset.assetName=e.name.toLowerCase();tile.hidden=!tile.dataset.assetName.includes(paShelf.query.toLowerCase());tile._libDrag=['project',e];tile.onclick=()=>paUse(e);grid.append(tile);}
  box.replaceChildren(tabs,el('p',{class:'note',text:'Current document: '+doc.name+'. Layers, source textures and saved conversions. Drag an asset onto the layer stack to reuse it.'}),el('div',{class:'chips'},search,seg([['s','S'],['m','M'],['l','L']],paShelf.size,v=>{paShelf.size=v;paRender();},'Project thumbnail size')),seg([['all','All'],['tex','Textures'],['mat','Materials']],paShelf.filter,v=>{paShelf.filter=v;paRender();},'Project asset type'),grid,items.length?null:el('p',{class:'note',text:'Paint a layer, send artwork from Paint, or turn a canvas into a texture or material. It will appear here.'}));}
async function paUse(e,T){const owner=doc.root;let rec,source,dispose=false;try{
  if(e.asset)rec=await pxDeep(e.asset.rec,false);if(doc.root!==owner)throw new Error('The document changed. Choose the asset again.');
  if(e.kind==='mat'){if(e.layer){rec={name:e.name,fill:fillClone(e.layer.fill),imgs:{}};const imgs=fillImgsOf(e.layer);insertAt=T?.at||null;try{return cmdNewFillLayer({name:rec.name,maps:rec.fill.maps,proj:rec.fill.proj,triSharp:rec.fill.triSharp,hStr:rec.fill.hStr,xf:rec.fill.xf,rep:rec.fill.rep,front:rec.fill.front,decal:rec.fill.decal,imgs});}finally{insertAt=null;}}
    insertAt=T?.at||null;try{return matApply(rec);}finally{insertAt=null;for(const t of Object.values(rec._t||{}))disposeTarget(t);}}
  source=e.source;if(rec){source=makeTarget(rec.w,rec.h,8,false);writeRegion(source,0,0,rec.w,rec.h,rec.data);dispose=true;}if(!source?.tex)throw new Error('This layer is no longer available.');
  if(T?.mask){const L=T.mask;selectOnly(L);const et=maskTargetOf(L);if(et)pictureIntoMask(et,source,0,0,doc.w,doc.h,'Project texture into mask');return;}
  insertAt=T?.at||null;try{return cmdNewFillLayer({name:e.name,maps:{base:{on:true,src:'image',name:e.name,tile:1}},proj:'uv',imgs:{base:source}});}finally{insertAt=null;}
 }catch(err){toast('Could not use the project asset: '+(err.message||err));}finally{if(dispose)disposeTarget(source);}}

/* Imported maps keep their source resolution. Consumers sample normalized UVs and scale only
   when an effect needs a document-size output. This also avoids expanding 2K maps into 16K copies. */
const P3_IMPORT_MAPS=['normal','ao','curv','curvEdge','curvCrease','thick','wnormal','position','id','height','rough','metal'];
function p3Resolution(){const n=Math.max(doc.w,doc.h),k=n>=1024&&n%1024===0?n/1024+'K · ':'';return k+doc.w+' × '+doc.h+' px';}
function p3ResolutionSync(){let b=$('#p3Resolution');if(ui.mode!=='p3d'){if(b)b.hidden=true;return;}if(!b){b=el('span',{id:'p3Resolution',class:'p3resolution',role:'status','aria-label':'3D Paint document resolution'});$('#work').append(b);}b.hidden=false;b.textContent=p3Resolution();b.classList.toggle('large',Math.max(doc.w,doc.h)>4096);b.title='Active texture set: '+doc.name+' · '+doc.depth+'-bit colour';}
function p3MapGuess(name){const s=baseName(name).toLowerCase().replace(/[ .-]+/g,'_');const pairs=[['wnormal',/world.*normal|normal.*world|wnormal/],['curvEdge',/curv.*edge|edge.*curv/],['curvCrease',/curv.*crease|crease.*curv/],['normal',/(^|_)(normal|normals|nrm|nor|normalgl|normaldx)(_|$)/],['ao',/(^|_)(ao|occlusion|ambientocclusion)(_|$)|ambient.*occlusion/],['curv',/curvature|curv/],['thick',/thickness|thick/],['position',/position|worldpos/],['id',/(^|_)(id|colorid|colourid|materialid)(_|$)/],['height',/height|displacement|disp/],['rough',/roughness|rough/],['metal',/metallic|metalness|metal/]];return pairs.find(([,re])=>re.test(s))?.[0]||null;}
function p3MapSet(k,t,name){if(!P3_IMPORT_MAPS.includes(k)||ui.mode!=='p3d')return false;const M=doc.meshMaps||(doc.meshMaps={}),old=M[k];M[k]=t;const meta=doc.meshMapInfo||(doc.meshMapInfo={});if(t)meta[k]={name:name||P3_MESHMAP_NAMES[k],w:t.w,h:t.h};else{delete M[k];delete meta[k];}if(old&&old!==t)disposeTarget(old);doc.meshMapVer=(doc.meshMapVer||0)+1;p3MeshMapsChanged();p3MapsRender();buildP3Panel();paRefresh();return true;}
async function p3MapImport(k,file){const root=doc.root;let t;try{loadStart(file.name);loadBusy('Reading mesh map…');await loadPaint();const raw=await decodeFile(file);
  if(raw.bits>8&&raw.w*raw.h>=268435456)throw new Error('Import this 16K mesh map at 8 bits per channel, or use a smaller source map.');
  const depth=k==='height'&&raw.bits>8&&canFloat?16:8,tex=uploadStraight(raw);try{t=makeTarget(raw.w,raw.h,depth,false);premultInto(t,tex,[0,0],null);}finally{gl.deleteTexture(tex);}setWrap(t,true);
  if(doc.root!==root||ui.mode!=='p3d')throw new Error('The texture set changed during import. Try again.');p3MapSet(k,t,file.name);t=null;toast('Attached '+file.name+' to '+P3_MESHMAP_NAMES[k]+' in “'+doc.name+'”.');
 }catch(e){if(t)disposeTarget(t);toast('Could not import '+file.name+': '+(e.message||e));}finally{loadEnd();}}
async function p3MapPick(k){const fs=await pickFiles('image/*,.tga,.dds,.tif,.tiff',false,P3_MESHMAP_NAMES[k],['png','jpg','jpeg','webp','tga','dds','tif','tiff','bmp']);if(fs[0])await p3MapImport(k,fs[0]);}
async function p3MapBatch(files){const root=doc.root;for(const f of files){if(doc.root!==root||ui.mode!=='p3d')return;const k=p3MapGuess(f.name);if(k)await p3MapImport(k,f);else toast('Choose a channel for “'+f.name+'”: drop it directly onto that map slot.');}}
function p3MapSlot(k){const t=doc.meshMaps?.[k],info=doc.meshMapInfo?.[k],row=el('div',{class:'meshslot'+(t?' filled':''),'data-mesh-slot':k},el('div',{class:'meshslotname',text:P3_MESHMAP_NAMES[k]}),el('div',{class:'meshslotfile',text:t?(info?.name||'Baked '+P3_MESHMAP_NAMES[k])+' · '+t.w+' × '+t.h:'Drop a map here'}),el('button',{class:'btn sm',text:t?'Replace…':'Import…',onclick:()=>p3MapPick(k)}));
  if(t)row.append(el('button',{class:'btn sm',text:'View',onclick:()=>p3mmSet(k)}),el('button',{class:'btn sm',text:'Edit in 2D',onclick:()=>p3MapEdit(k)}),el('button',{class:'btn sm',text:'×',title:'Remove '+P3_MESHMAP_NAMES[k],'aria-label':'Remove '+P3_MESHMAP_NAMES[k],onclick:()=>p3MapSet(k,null)}));
  row.addEventListener('dragover',e=>{if([...e.dataTransfer.types].includes('Files')){e.preventDefault();e.stopPropagation();row.classList.add('dropon');e.dataTransfer.dropEffect='copy';}});row.addEventListener('dragleave',()=>row.classList.remove('dropon'));row.addEventListener('drop',e=>{e.preventDefault();e.stopPropagation();row.classList.remove('dropon');const f=e.dataTransfer.files[0];if(f)p3MapImport(k,f);});return row;}
function p3MapSlots(){return el('div',{class:'meshslots'},...P3_IMPORT_MAPS.map(p3MapSlot));}
function p3MapsRender(){const box=$('#meshMapSlots');if(!box)return;box.hidden=ui.mode!=='p3d';if(box.hidden){box.replaceChildren();return;}box.replaceChildren(el('div',{class:'sub',text:'Mesh maps · '+doc.name}),el('p',{class:'note',text:'Drop files into their channels. These maps feed normals, material channels, masks and generators for this texture set.'}),p3MapSlots());if(typeof dlg!=='undefined'&&dlg?._meshDraw)dlg._meshDraw();}
function p3MeshLibrary(){const box=$('#mmBody');if(!box||!paVisible('#mmBody'))return;const grid=el('div',{class:'matgrid projectgrid'});grid.style.setProperty('--tw',matTw()+'px');
  for(const k of p3mmKeys()){const t=doc.meshMaps[k],e={kind:'meshmap',k,name:doc.meshMapInfo?.[k]?.name||P3_MESHMAP_NAMES[k],t},tile=el('button',{class:'mattile',title:e.name+' · '+t.w+' × '+t.h+' — drag to a map slot',type:'button'},el('img',{class:'matprev',src:paPreview(t),alt:''}),el('span',{text:P3_MESHMAP_NAMES[k]}),el('small',{text:t.w+' × '+t.h}));tile._libDrag=['meshmap',e];tile.onclick=()=>p3mmSet(k);grid.append(tile);}
  box.replaceChildren(el('div',{class:'chips'},el('button',{class:'btn sm',text:'Import mesh maps…',onclick:async()=>{const files=await pickFiles('image/*,.tga,.dds,.tif,.tiff',true,'Mesh maps',['png','jpg','jpeg','webp','tga','dds','tif','tiff','bmp']);await p3MapBatch(files);}}),el('button',{class:'btn sm',text:'Assign in Maps',onclick:()=>{showPanel('maps');p3MapsRender();}})),el('p',{class:'note',text:'Mesh maps for “'+doc.name+'”. Click to inspect on the model, or drag onto a channel in Maps. Bake or import maps to populate this shelf.'}),grid);}
async function p3MapLibraryDrop(rec,k){const t=makeTarget(rec.t.w,rec.t.h,rec.t.depth,false);copyScaled(rec.t,t);setWrap(t,true);p3MapSet(k,t,rec.name);}
