/* Directional depth shadows, cached across camera navigation.
   A transparent catcher plane receives actual mesh shadows; it is not a painted oval. */
const STUDIO_SHADOW_GLSL=`uniform sampler2D uShadow; uniform mat4 uShadowVP; uniform float uShadowOn; uniform float uShadowSoft;
float studioVisibility(vec3 p,vec3 N,vec3 L){if(uShadowOn<0.5)return 1.0;vec4 q=uShadowVP*vec4(p,1.0);vec3 c=q.xyz/q.w*0.5+0.5;
 if(c.x<0.0||c.x>1.0||c.y<0.0||c.y>1.0||c.z>1.0||c.z<0.0)return 1.0;float bias=max(0.00012,0.0009*(1.0-max(dot(N,L),0.0))),v=0.0;
 vec2 stepUV=vec2(max(uShadowSoft,0.5))/vec2(textureSize(uShadow,0));for(int y=-1;y<=1;y++)for(int x=-1;x<=1;x++)v+=c.z-bias<=texture(uShadow,c.xy+vec2(x,y)*stepUV).r?1.0:0.0;return v/9.0;}`;
const STUDIO_LIGHT_GLSL=`uniform float uStudioFill; uniform float uStudioRim; uniform vec3 uLightColor;
vec3 studioDirect(vec3 N,vec3 V,vec3 L,vec3 albedo,vec3 f0,float r,float metal){float nl=max(dot(N,L),0.0),nv=max(dot(N,V),0.001);vec3 H=normalize(V+L);
 float nh=max(dot(N,H),0.0),vh=max(dot(V,H),0.0),a2=pow(r,4.0),d=nh*nh*(a2-1.0)+1.0,D=a2/(3.14159265*d*d);
 float vis=0.5/max(nl*sqrt(nv*nv*(1.0-a2)+a2)+nv*sqrt(nl*nl*(1.0-a2)+a2),0.0001);vec3 f=f0+(1.0-f0)*pow(1.0-vh,5.0);
 return ((1.0-f)*(1.0-metal)*albedo/3.14159265+D*vis*f)*nl;}`;
const studioShadow={mesh:null,key:null,fbo:null,tex:null,size:0,VP:null,floorVAO:null,floorVB:null,prog:null,floorProg:null,bounds:new WeakMap(),builds:0};
function studioBounds(m){let b=studioShadow.bounds.get(m);if(b)return b;const lo=[Infinity,Infinity,Infinity],hi=[-Infinity,-Infinity,-Infinity];
 for(let i=0;i<m.pos.length;i+=3)for(let j=0;j<3;j++){lo[j]=Math.min(lo[j],m.pos[i+j]);hi[j]=Math.max(hi[j],m.pos[i+j]);}b={lo,hi};studioShadow.bounds.set(m,b);return b;}
function studioFloorY(){const m=v3.mesh;if(!m)return -1;return studioBounds(m).lo[1]-(v3s().disp||0)*.15+(v3s().floorHeight||0);}
function studioShadowPrepare(C,list){const s=C.s,S=studioShadow,on=s.shadows!==false&&!C.bake&&!C.mv&&!v3Unlit();if(!on)return {uShadow:dummy,uShadowVP:{m4:m4()},uShadowOn:0,uShadowSoft:1};
 const m=v3.mesh,size=['low','medium'].includes(prefs.quality)?1024:2048,texVersion=s.disp?doc.root._compVer||doc.count+hist.undo.length:0;
 const key=JSON.stringify([s.sunAz,s.sunEl,s.disp,texVersion,s.clip,size,list.map(t=>[t.start,t.count,t.T.height?.tex&&s.disp?t.T.height._studioVer||hist.undo.length:0,s.clip?t.T.base?._studioVer||0:0,s.clip?t.T.opac?._studioVer||0:0])]);
 if(S.mesh!==m||S.key!==key||S.size!==size){if(S.size!==size){if(S.tex)gl.deleteTexture(S.tex);if(S.fbo)gl.deleteFramebuffer(S.fbo);S.size=size;S.tex=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,S.tex);gl.texImage2D(gl.TEXTURE_2D,0,gl.DEPTH_COMPONENT24,size,size,0,gl.DEPTH_COMPONENT,gl.UNSIGNED_INT,null);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);S.fbo=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,S.fbo);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,gl.TEXTURE_2D,S.tex,0);gl.drawBuffers([gl.NONE]);gl.readBuffer(gl.NONE);if(gl.checkFramebufferStatus(gl.FRAMEBUFFER)!==gl.FRAMEBUFFER_COMPLETE)throw new Error('Shadow framebuffer unavailable');}
   if(!S.prog)S.prog=prog3(VS_3D,'in vec2 vT;uniform sampler2D uBase;uniform sampler2D uOpac;uniform int uClip;uniform int uHasOpac;void main(){float a=texture(uBase,vT).a;if(uHasOpac==1)a*=texture(uOpac,vT).r;if(uClip==1&&a<0.5)discard;o=vec4(1.0);}');const r=Math.max(m.radius,1),light=[Math.cos(C.e)*Math.sin(C.a),Math.sin(C.e),Math.cos(C.e)*Math.cos(C.a)],eye=light.map(v=>v*r*5),V=m4look(eye,[0,0,0],Math.abs(light[1])>.98?[0,0,1]:[0,1,0]),O=m4();O[0]=O[5]=1/(r*2.4);O[10]=-2/(r*12);O[14]=-1;O[15]=1;S.VP=m4mul(O,V);
   gl.bindFramebuffer(gl.FRAMEBUFFER,S.fbo);gl.viewport(0,0,size,size);gl.enable(gl.DEPTH_TEST);gl.disable(gl.BLEND);gl.depthMask(true);gl.clearDepth(1);gl.clear(gl.DEPTH_BUFFER_BIT);gl.bindVertexArray(v3.gpu.vao);gl.enable(gl.POLYGON_OFFSET_FILL);gl.polygonOffset(1.5,2);
   for(const it of list){if(!it.count)continue;useProg(S.prog,{uVP:{m4:S.VP},uUVs:s.uvs,uBase:it.T.base?.tex||dummy,uOpac:it.T.opac?.tex||dummy,uHasOpac:!!it.T.opac,uClip:!!s.clip,uH:it.T.height?.tex||dummy,uDisp:s.disp*.3,uUseH:!!(it.T.height&&s.disp)});gl.drawElements(gl.TRIANGLES,it.count*3,gl.UNSIGNED_INT,it.start*12);}gl.disable(gl.POLYGON_OFFSET_FILL);S.mesh=m;S.key=key;S.builds++;}
 return {uShadow:S.tex,uShadowVP:{m4:S.VP},uShadowOn:1,uShadowSoft:s.shadowSoft||1.5};}
function studioFloorDraw(C,VP,F,SU){if(!C.s.floor||C.bake||C.mv||v3Unlit())return;const S=studioShadow,r=Math.max(v3.mesh.radius,1)*3.5;
 if(!S.floorProg)S.floorProg=prog3(`#version 300 es
layout(location=0) in vec3 aP; uniform mat4 uVP; uniform float uFloorY; uniform float uRadius; out vec3 vP;void main(){vP=aP*uRadius;vP.y=uFloorY;gl_Position=uVP*vec4(vP,1.0);}`,
 `in vec3 vP;uniform vec3 uSun;uniform float uFloorOpacity;uniform vec3 uFloorColor;uniform float uRadius;${STUDIO_SHADOW_GLSL}
void main(){float a=(1.0-studioVisibility(vP,vec3(0.0,1.0,0.0),uSun))*uFloorOpacity;float edge=1.0-smoothstep(0.75,1.0,max(abs(vP.x),abs(vP.z))/uRadius);a*=edge;if(a<0.001)discard;o=vec4(uFloorColor,a);}`);
 if(!S.floorVAO){S.floorVAO=gl.createVertexArray();gl.bindVertexArray(S.floorVAO);S.floorVB=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,S.floorVB);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,0,-1,1,0,-1,1,0,1,-1,0,-1,1,0,1,-1,0,1]),gl.STATIC_DRAW);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,3,gl.FLOAT,false,12,0);}
 gl.bindFramebuffer(gl.FRAMEBUFFER,F.ms);gl.viewport(0,0,F.w,F.h);gl.bindVertexArray(S.floorVAO);gl.enable(gl.DEPTH_TEST);gl.enable(gl.BLEND);gl.blendFuncSeparate(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA,gl.ONE,gl.ONE_MINUS_SRC_ALPHA);gl.depthMask(false);
 useProg(S.floorProg,{...SU,uShadowSoft:C.s.floorSoft||2,uFloorColor:C.s.floorColor||[0,0,0],uVP:{m4:VP},uFloorY:studioFloorY(),uRadius:r,uFloorOpacity:C.s.floorOpacity??.5,uSun:[Math.cos(C.e)*Math.sin(C.a),Math.sin(C.e),Math.cos(C.e)*Math.cos(C.a)]});gl.drawArrays(gl.TRIANGLES,0,6);gl.depthMask(true);gl.disable(gl.BLEND);gl.bindVertexArray(v3.gpu.vao);}
function studioLightingPreset(k){const presets={soft:{sunAz:35,sunEl:55,envSun:.55,studioFill:.22,studioRim:.2,shadowSoft:2.5,lightColor:[1,.97,.93]},product:{sunAz:55,sunEl:40,envSun:1,studioFill:.12,studioRim:.5,shadowSoft:1.5,lightColor:[1,.95,.88]},neutral:{sunAz:0,sunEl:55,envSun:.65,studioFill:.3,studioRim:.05,shadowSoft:2,lightColor:[1,1,1]}};Object.assign(v3s(),presets[k]||presets.soft);v3.dirty=true;requestRender();build3dPane();renderShading();}
function studioSettingsBox(S,prefix='v3'){const id=s=>prefix+s,slider=(name,...a)=>S(id(name),...a);const s=v3s(),set=(key,v)=>{s[key]=v;v3.dirty=true;requestRender();};return el('div',{class:'dlg-grid'},el('div',{class:'sub',text:'Studio lighting'}),seg([['soft','Soft studio'],['product','Product'],['neutral','Neutral']],null,studioLightingPreset,'Studio lighting preset'),
 slider('Fill','Fill light','studioFill',0,2,.01,pct),slider('Rim','Rim light','studioRim',0,2,.01,pct),colourBtn(id('KeyColor'),()=>s.lightColor||[1,1,1],c=>set('lightColor',c),'Key light colour'),chk(id('Shadows'),'Mesh shadows',s.shadows!==false,v=>set('shadows',v)),slider('ShadowSoft','Shadow softness','shadowSoft',.5,4,.1,v=>v.toFixed(1)),
 el('div',{class:'sub',text:'Shadow floor'}),chk(id('Floor'),'Transparent shadow floor',!!s.floor,v=>{set('floor',v);if(v)s.shadows=true;}),slider('FloorHeight','Floor height','floorHeight',-2,2,.005,v=>v.toFixed(3)),slider('FloorAz','Shadow direction','sunAz',0,360,1,v=>v+'°'),slider('FloorEl','Light height','sunEl',5,90,1,v=>v+'°'),slider('FloorSoft','Floor shadow softness','floorSoft',.5,6,.1,v=>v.toFixed(1)),colourBtn(id('FloorColor'),()=>s.floorColor||[0,0,0],c=>set('floorColor',c),'Floor shadow colour'),slider('FloorOpacity','Shadow opacity','floorOpacity',0,1,.01,pct),el('button',{class:'btn sm',text:'Place floor under mesh',onclick:()=>set('floorHeight',0)}),el('p',{class:'note',text:'The floor sits under the mesh automatically. Only its shadows are visible. Height moves it above or below that position.'}));}
