const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),http=require('http');
let fails=0;const ok=(v,m)=>{console.log((v?'PASS ':'FAIL ')+m);if(!v)fails++;};
(async()=>{
const root=path.resolve(__dirname,'../../dist'),server=http.createServer((req,res)=>{const f=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!f.startsWith(root+path.sep)||!fs.existsSync(f)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',f.endsWith('.html')?'text/html':'application/octet-stream');fs.createReadStream(f).pipe(res);});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;
const b=await chromium.connectOverCDP(process.env.GS_NATIVE_CDP),p=b.contexts()[0].pages()[0],errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',r=>r.request().url().startsWith(url)?r.continue():r.abort());await p.goto(url+'/index.html?debug');await p.waitForFunction(()=>window.__gs);await p.evaluate(()=>{const G=__gs;G.closeWelcome();G.newDoc(64,64,8,[.2,.4,.6],'Shortcut test',false);G.setMode('anim',true);G.doc.anim.frames[0].hold=3;});
const snapshot=()=>{const G=__gs,A=G.doc.anim,F=A.frames[A.cur];return {count:A.frames.length,cur:A.cur,hold:F.hold,pixels:Array.from(G.readRGBA8(F.target)),selected:G.sel.active};};
const before=await p.evaluate(snapshot);await p.keyboard.press('Shift+D');const copy=await p.evaluate(snapshot);ok(copy.count===before.count+1&&copy.cur===before.cur+1&&copy.hold===3&&JSON.stringify(copy.pixels)===JSON.stringify(before.pixels),'Shift+D duplicates pixels and hold after the current frame');
await p.keyboard.press('Control+z');ok(await p.evaluate(()=>__gs.doc.anim.frames.length)===before.count,'duplicate undoes');await p.keyboard.press('Control+Shift+z');ok(await p.evaluate(()=>__gs.doc.anim.frames.length)===copy.count,'duplicate redoes');
await p.keyboard.press('Control+a');ok(await p.evaluate(()=>__gs.sel.active),'select all works');await p.keyboard.press('Control+d');ok(await p.evaluate(()=>!__gs.sel.active&&__gs.doc.anim.frames.length)===copy.count,'Ctrl+D deselects without adding a frame');await p.keyboard.press('Control+Shift+d');ok(await p.evaluate(()=>__gs.sel.active&&__gs.doc.anim.frames.length)===copy.count,'Ctrl+Shift+D reselects without adding a frame');
await p.keyboard.down('Shift');await p.keyboard.down('d');await p.keyboard.down('d');await p.keyboard.down('d');await p.keyboard.up('d');await p.keyboard.up('Shift');ok(await p.evaluate(()=>__gs.doc.anim.frames.length)===copy.count+1,'held Shift+D makes a single copy');
const count=await p.evaluate(()=>__gs.doc.anim.frames.length);await p.locator('[aria-label="Frames per second"]').focus();await p.keyboard.press('Shift+D');ok(await p.evaluate(()=>__gs.doc.anim.frames.length)===count,'typing in a field does not duplicate');await p.locator('[aria-label="Frames per second"]').evaluate(e=>e.blur());await p.keyboard.press('Control+Shift+Alt+d');ok(await p.evaluate(()=>__gs.doc.anim.frames.length)===count,'Alt-modified shortcut does not duplicate');
ok(await p.locator('#timeline button[title="Copy this frame (Shift+D)"]').count()===1,'Duplicate button advertises Shift+D');await p.evaluate(()=>__gs.setMode('paint',true));await p.keyboard.press('Shift+D');ok(await p.evaluate(()=>__gs.doc.anim.frames.length)===count,'Shift+D does not duplicate frames outside Animation');
await p.evaluate(()=>__gs.dlgWhatsNew());ok(await p.locator('#dlgBody').innerText().then(s=>s.includes('0.51.5')&&s.includes('Shift+D')),'What\'s new includes the shortcut change');ok(!errors.length,'no app errors');await b.close();server.closeAllConnections();await new Promise(r=>server.close(r));process.exit(fails?1:0);
})().catch(e=>{console.error(e);process.exit(1);});
