/* Shared-context bake/view regression, steady minification at 8K, Clear and Preferences. */
const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),http=require('http');
const root=path.resolve(__dirname,'../../dist'),out=path.resolve(__dirname,'out/paths0480');let fails=0;const ok=(c,m)=>{console.log((c?'PASS ':'FAIL ')+m);if(!c)fails++;};
(async()=>{const server=http.createServer((req,res)=>{const f=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!f.startsWith(root+path.sep)||!fs.existsSync(f)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',f.endsWith('.html')?'text/html':'application/octet-stream');fs.createReadStream(f).pipe(res);});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;
 const native=process.env.GS_NATIVE_CDP,b=native?await chromium.connectOverCDP(native):await chromium.launch({channel:'msedge',headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']}),p=native?b.contexts()[0].pages()[0]:await b.newPage({viewport:{width:1500,height:1000}}),errors=[];p.setDefaultTimeout(60000);p.on('pageerror',e=>errors.push(e.stack));
 await p.addInitScript(()=>{localStorage.setItem('gs.p3d',JSON.stringify({size:128,layout:'3d'}));localStorage.setItem('gs.welcome','no');});await p.route('**/*',r=>r.request().url().startsWith(url)?r.continue():r.abort());await p.goto(url+'/index.html?debug');await p.waitForFunction(()=>window.__gs);await p.evaluate(()=>{__gs.closeWelcome();__gs.newDoc(128,128,8,null,'Bake viewport',false);__gs.setMode('p3d',true);});
 const bake=await p.evaluate(async()=>{const g=__gs,gl=g.gl,low=g.parseOBJ('v -1 -1 0\nv 1 -1 0\nv 1 1 0\nv -1 1 0\nvt 0 0\nvt 1 0\nvt 1 1\nvt 0 1\nf 1/1 2/2 3/3 4/4\n','bake-plane.obj'),high=g.parseOBJ('v -1 -1 .02\nv 1 -1 .02\nv 1 1 .02\nv -1 1 .02\nf 1 2 3 4\n','high-plane.obj'),opts={size:512,ss:2,kinds:['normal','ao','height'],front:.1,back:.1,rays:32,aoDist:.5,thickDist:1,dx:false,pad:18,seed:1.3},progress={cancelled:false,set(){},step(){}};
   const plain=await g.bakeRun(low,high,opts,progress),expected={};for(const k in plain){expected[k]=Array.from(g.captureRegionNow(plain[k],0,0,512,512).data);g.disposeTarget(plain[k]);}
   let frames=0,leaked=0,black=0,angle=g.v3.cam.yaw;const timer=setInterval(()=>{if(gl.isEnabled(gl.SCISSOR_TEST))leaked++;g.v3.cam.yaw+=.02;g.v3.dirty=true;g.drawView();gl.bindFramebuffer(gl.FRAMEBUFFER,null);const pixel=new Uint8Array(4);gl.readPixels(5,5,1,1,gl.RGBA,gl.UNSIGNED_BYTE,pixel);if(pixel[0]+pixel[1]+pixel[2]<3)black++;g.draw3D();frames++;},0);
   let result;try{result=await g.bakeRun(low,high,opts,progress);}finally{clearInterval(timer);}const same=Object.keys(result).every(k=>{const got=g.captureRegionNow(result[k],0,0,512,512).data;return expected[k].every((v,i)=>v===got[i]);});for(const k in result)g.disposeTarget(result[k]);return {frames,leaked,black,same,rotated:g.v3.cam.yaw!==angle,error:gl.getError()};});console.log('Bake/view',bake);ok(bake.frames>10&&bake.rotated&&bake.leaked===0&&bake.black===0,'viewport keeps rotating during AO bake without leaked clipping or black clear flashes');ok(bake.same&&bake.error===0,'interleaved viewport rendering leaves baked map pixels identical to a stationary bake');
 await p.evaluate(()=>{__gs.setMode('paint',true);__gs.newDoc(128,128,8,null,'Clear test',false);__gs.setDocMaps(['base','rough']);const L=__gs.doc.active;__gs.clearTarget(L.target,[.5,.2,.1,1]);__gs.clearTarget(__gs.ensureMapTarget(L,'rough'),[.4,.4,.4,1]);__gs.requestRender(true);});await p.locator('#lClear').click();ok(await p.evaluate(()=>['base','rough'].every(k=>__gs.captureRegionNow(__gs.mapT(__gs.doc.active,k),64,64,1,1).data[3]===0)),'Clear layer button clears all painted channels');await p.evaluate(()=>__gs.undo());ok(await p.evaluate(()=>['base','rough'].every(k=>__gs.captureRegionNow(__gs.mapT(__gs.doc.active,k),64,64,1,1).data[3]===255)),'Clear layer is one undo step across channels');
 await p.evaluate(()=>__gs.cmdNewFillLayer({name:'Clear material',maps:{base:{on:true,src:'value',c:[.3,.4,.5]},rough:{on:true,src:'value',v:.3}}}));await p.locator('#lClear').click();ok(await p.evaluate(()=>__gs.doc.active.mask&&__gs.captureRegionNow(__gs.doc.active.mask.target,64,64,1,1).data[0]===0),'Clear material layer removes its appearance and retains the material recipe');await p.evaluate(()=>__gs.undo());ok(await p.evaluate(()=>!__gs.doc.active.mask),'undo restores the material without its temporary clear mask');
 await p.evaluate(()=>__gs.dlgPrefs());const dialog=p.locator('#modal .dialog'),r=await dialog.boundingBox();await p.mouse.move(r.x+r.width-2,r.y+r.height-2);await p.mouse.down();await p.mouse.move(r.x+r.width+180,r.y+r.height+65,{steps:8});await p.mouse.up();const resized=await dialog.boundingBox();ok(resized.width>r.width+100&&resized.height>r.height+25,'Preferences resizes using its corner');await p.screenshot({path:path.join(out,'preferences-resized-desktop.png')});await p.locator('#dlgCancel').click();await p.evaluate(()=>__gs.dlgPrefs());const reopened=await dialog.boundingBox();console.log('Preferences bounds',{r,resized,reopened,stored:await p.evaluate(()=>localStorage.getItem('gs.prefSize'))});ok(Math.abs(reopened.width-resized.width)<3&&Math.abs(reopened.height-resized.height)<3,'Preferences remembers the resized size');await p.locator('#dlgCancel').click();
 if(native){const canvas=await p.evaluate(()=>{const g=__gs,gl=g.gl;g.newDoc(8192,8192,8,null,'8K steady canvas',false);g.setTool('brush');const L=g.doc.active,shader=g.program('void main(){vec2 q=floor(gl_FragCoord.xy/3.0);float a=mod(q.x+q.y,2.0);o=vec4(vec3(a),1.0);}');g.run(shader,L.target,{});g.composite();g.drawView();const x=Math.round(g.view.x*g.dprNow()+100),y=g.cvCanvas.height-Math.round(g.view.y*g.dprNow()+100),read=()=>{gl.bindFramebuffer(gl.FRAMEBUFFER,null);const u=new Uint8Array(32*32*4);gl.readPixels(x,y,32,32,gl.RGBA,gl.UNSIGNED_BYTE,u);return u;},before=read();let count=0;const generate=gl.generateMipmap.bind(gl);gl.generateMipmap=function(t){count++;return generate(t);};
    try{const et=g.editTarget(),o={...g.brush,tool:'brush',size:64,pSize:false,hardness:1,color:[1,0,0],sel:false};g.beginStroke(L,6000,6000,1,o);g.addPoint(6100,6000,1);g.composite();g.drawView();const during=read(),first=count;g.addPoint(6200,6000,1);g.composite();g.drawView();const regional=count-first;g.endStroke(true);g.composite();g.drawView();const after=read();return {difference:before.reduce((n,v,i)=>Math.max(n,Math.abs(v-during[i]),Math.abs(v-after[i])),0),regional,mips:g.compOut().hasMips,error:gl.getError()};}finally{gl.generateMipmap=generate;}});console.log('8K canvas',canvas);ok(canvas.difference<=1&&canvas.mips,'untouched 8K canvas detail stays identical during and after a stroke');ok(canvas.regional===0&&canvas.error===0,'8K continuing strokes update only affected mip regions without regenerating the full image');}
 ok(errors.length===0,'no application errors');if(errors.length)console.log(errors);await b.close();await new Promise(r=>server.close(r));process.exit(fails?1:0);
})().catch(e=>{console.error(e);process.exit(1);});
