const {chromium}=require('playwright');
const OLD=__dirname+'/';
const OUT=__dirname+'/out/';
let fails=0;const ok=(c,m)=>{console.log((c?'PASS ':'FAIL ')+m);if(!c)fails++;};
(async()=>{
 const b=await chromium.launch({args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const ctx=await b.newContext({viewport:{width:1440,height:1000}});const p=await ctx.newPage();
 await p.route('**/*',r=>{const u=r.request().url();
  if(u.includes('pako'))return r.fulfill({path:OLD+'node_modules/pako/dist/pako.min.js',contentType:'text/javascript'});
  if(u.includes('UTIF.js'))return r.fulfill({path:OLD+'node_modules/utif/UTIF.js',contentType:'text/javascript'});
  if(u.includes('ag-psd'))return r.fulfill({path:OLD+'node_modules/ag-psd/dist/bundle.js',contentType:'text/javascript'});
  if(u.startsWith('file:'))return r.continue();return r.abort();});
 const errs=[];p.on('pageerror',e=>errs.push('PAGEERR '+e.stack));p.on('console',m=>{if(m.type()==='error'&&!m.text().includes('ERR_'))errs.push(m.text());if(m.type()==='warning'&&/GL|WebGL/.test(m.text()))errs.push('GLWARN '+m.text());});
 await p.goto('file://'+require('path').resolve(__dirname,'../../dist-web/index.html')+'?debug');await p.waitForTimeout(2500);
 const box=await p.locator('#gl').boundingBox();
 const scr=async(x,y)=>{const v=await p.evaluate(()=>({x:__gs.view.x,y:__gs.view.y,z:__gs.view.zoom}));return [box.x+v.x+x*v.z,box.y+v.y+y*v.z];};
 const drag=async(x0,y0,x1,y1,opts={})=>{const a=await scr(x0,y0),c=await scr(x1,y1);await p.mouse.move(a[0],a[1]);await p.mouse.down();await p.mouse.move(c[0],c[1],{steps:opts.steps||8});await p.mouse.up();await p.waitForTimeout(120);};
 const mpx=(name,k,pts)=>p.evaluate(([name,k,pts])=>{const L=__gs.layerByName(name),t=__gs.mapT(L,k);if(!t||t.empty)return null;const d=__gs.readRGBA8(t),W=__gs.doc.w;return pts.map(([x,y])=>Array.from(d.slice((y*W+x)*4,(y*W+x)*4+4)));},[name,k,pts]);
 const setFG=async hx=>{await p.fill('#hex',hx);await p.press('#hex','Enter');};

 const fs=require('fs');
 await p.evaluate(()=>__gs.newDoc(256,256,8,[.5,.5,.5],'bake',false));
 const txt=fs.readFileSync(__dirname+'/fixtures/high.obj','utf8');
 const t0=Date.now();
 const r=await p.evaluate(async txt=>{const C=__gs.bakeCfg;C.high=__gs.parseOBJ(txt,'high');C.ss=1;C.rays=96;C.pad=8;C.front=15;C.back=5;
   Object.assign(C.kinds,{normal:true,ao:true,curv:true,height:true,thick:true,wnormal:true,position:true,id:true});
   await __gs.runBake(__gs.bakeViewModel(),Object.keys(C.kinds));
   const out={maps:__gs.doc.maps.join(),layers:__gs.allLayers().map(l=>l.name)};return out;},txt);
 console.log('bake ms',Date.now()-t0,JSON.stringify(r));
 await p.waitForTimeout(500);
 const mp=(name,k,pts)=>p.evaluate(([name,k,pts])=>{const L=__gs.layerByName(name),t=__gs.mapT(L,k),d=__gs.readRGBA8(t),W=__gs.doc.w;return pts.map(([x,y])=>Array.from(d.slice((y*W+x)*4,(y*W+x)*4+4)));},[name,k,pts]);
 const n=await mp('Baked normal','normal',[[128,128],[128+40,128],[128-40,128],[128,128-40],[128,128+40],[10,10]]);
 console.log('normal',JSON.stringify(n));
 ok(n[1][0]>150&&n[2][0]<105&&n[3][1]>150&&n[4][1]<105&&Math.abs(n[5][0]-128)<4,'normal tilts outward around the bump (GL: up = green) ');
 const h=await mp('Baked height','height',[[128,128],[10,10]]);ok(h[0][0]>h[1][0]+30,'height raised at bump '+JSON.stringify(h));
 const a=await mp('Baked AO','ao',[[128,128],[128+66,128],[10,10]]);console.log('ao',JSON.stringify(a));ok(a[1][0]<a[2][0],'AO darker at bump foot');
 await p.screenshot({path:OUT+'bake.png'});
 ok(errs.length===0,'no errors '+errs.slice(0,3).join('\n'));
 console.log(fails?fails+' FAILED':'ALL PASSED');await b.close();})();
