const {chromium}=require('playwright');
const OLD=__dirname+'/';
const OUT=__dirname+'/out/';
let fails=0;const ok=(c,m)=>{console.log((c?'PASS ':'FAIL ')+m);if(!c)fails++;};
(async()=>{
 const b=await chromium.launch({args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const ctx=await b.newContext({viewport:{width:1440,height:900}});const p=await ctx.newPage();
 await p.route('**/*',r=>{const u=r.request().url();
  if(u.includes('pako'))return r.fulfill({path:OLD+'node_modules/pako/dist/pako.min.js',contentType:'text/javascript'});
  if(u.includes('UTIF.js'))return r.fulfill({path:OLD+'node_modules/utif/UTIF.js',contentType:'text/javascript'});
  if(u.includes('ag-psd'))return r.fulfill({path:OLD+'node_modules/ag-psd/dist/bundle.js',contentType:'text/javascript'});
  if(u.startsWith('file:'))return r.continue();return r.abort();});
 const errs=[];p.on('pageerror',e=>errs.push('PAGEERR '+e.stack));p.on('console',m=>{if(m.type()==='error'&&!m.text().includes('ERR_'))errs.push(m.text());if(m.type()==='warning'&&/GL|WebGL/.test(m.text()))errs.push('GLWARN '+m.text());});
 await p.goto('file://'+require('path').resolve(__dirname,'../../dist-web/index.html')+'?debug');await p.waitForTimeout(2500);
 const IMG=require('path').resolve(__dirname,'../../docs/wiki/images')+'/';const W=ms=>p.waitForTimeout(ms||300);
 const waitIdle=async()=>{for(let i=0;i<1200;i++){if(await p.evaluate(()=>!__gs.bk.busy&&!__gs.bk.regionBusy))return;await W(100);}};
 const setFG=async hx=>{await p.fill('#hex',hx);await p.press('#hex','Enter');};
 await p.addScriptTag({path:__dirname+'/fixtures/bumpy.js'});
 await p.evaluate(()=>{__gs.newDoc(1024,1024,8,[.55,.5,.45],'Rock',false);});await W(400);
 await p.click('#modeTabs [data-mode=bake]');await W(600);
 await p.evaluate(()=>{const C=__gs.bakeCfg;const lo=__gs.primMesh('sphere',0);lo.name='rock_low';C.low=lo;const hi=__bumpy(__gs.primMesh('sphere',4));hi.name='rock_high';C.high=hi;C.ss=2;C.pad=8;C.front=6;C.back=6;C.rays=16;for(const k in C.kinds)C.kinds[k]=['normal','curv'].includes(k);});
 await p.evaluate(()=>{__gs.act('bake');});await p.click('#modeTabs [data-mode=paint]');await W(200);await p.click('#modeTabs [data-mode=bake]');await W(500);
 await p.click('#bkGo');for(let i=0;i<400;i++){if(await p.evaluate(()=>(__gs.bk.tiles||0)>=6||!__gs.bk.busy))break;await W(100);}await p.screenshot({path:IMG+'bake-progress.png',timeout:180000});await waitIdle();await W(800);
 await p.mouse.move(5,300);await p.screenshot({path:IMG+'bake-tab.png'});
 await p.evaluate(()=>{const b=[...document.querySelectorAll('#bakeBody .seg button')].find(b=>b.textContent==='Skew');b.click();});await W(300);
 await setFG('#000000');await p.evaluate(()=>Object.assign(__gs.brush,{size:70,hardness:.6,opacity:1,flow:1,smoothing:.3,pSize:false,tip:null}));
 const hb=await p.locator('#v3Hit').boundingBox();const cx=hb.x+hb.width/2,cy=hb.y+hb.height/2;
 await p.mouse.move(cx-120,cy-60);await p.mouse.down();for(let i=0;i<=20;i++){await p.mouse.move(cx-120+i*10,cy-60+Math.sin(i/3)*30);}await p.mouse.up();await waitIdle();await W(600);
 await p.mouse.move(cx+60,cy+40);await p.screenshot({path:IMG+'bake-skew.png'});
 await p.click('#modeTabs [data-mode=paint]');await W(600);
 await p.evaluate(()=>{__gs.newDoc(1024,1024,8,[.35,.52,.33],'Painted',false);});await W(300);
 if(!(await p.evaluate(()=>__gs.v3.on)))await p.keyboard.press('F3');await W(500);
 await p.selectOption('#v3Model','sphere');await W(500);await p.keyboard.press('b');
 if(!(await p.evaluate(()=>__gs.v3.paintOn)))await p.click('#v3Paint');
 await p.evaluate(()=>Object.assign(__gs.brush,{size:28,hardness:.8,smoothing:.3}));
 const hb2=await p.locator('#v3Hit').boundingBox();const x2=hb2.x+hb2.width/2,y2=hb2.y+hb2.height/2;
 const cols=['#f2c14e','#f78154','#5fad56','#4d9de0'];
 for(let r=0;r<4;r++){await setFG(cols[r]);await p.mouse.move(x2-150,y2-90+r*55);await p.mouse.down();for(let i=0;i<=30;i++)await p.mouse.move(x2-150+i*10,y2-90+r*55+Math.sin(i/2.5)*14);await p.mouse.up();await W(150);}
 await W(700);await p.mouse.move(x2+40,y2+120);await p.screenshot({path:IMG+'paint-on-model.png'});
 ok(errs.length===0,'no errors '+errs.join('\n'));
 console.log(fails?fails+' FAILED':'ALL PASSED');await b.close();
})();
