const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),http=require('http');
const root=path.resolve(__dirname,'../../dist'),out=path.resolve(__dirname,'out/brush0512');fs.mkdirSync(out,{recursive:true});let fails=0;
const ok=(v,m)=>{console.log((v?'PASS ':'FAIL ')+m);if(!v)fails++;};
(async()=>{
const server=http.createServer((req,res)=>{const f=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!f.startsWith(root+path.sep)||!fs.existsSync(f)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',f.endsWith('.html')?'text/html':'application/octet-stream');fs.createReadStream(f).pipe(res);});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;
const native=process.env.GS_NATIVE_CDP,b=native?await chromium.connectOverCDP(native):await chromium.launch({channel:'msedge',headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']}),p=native?b.contexts()[0].pages()[0]:await b.newPage({viewport:{width:1500,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));await p.route('**/*',r=>r.request().url().startsWith(url)?r.continue():r.abort());await p.goto(url+'/index.html?debug');await p.waitForFunction(()=>window.__gs);await p.evaluate(()=>{__gs.closeWelcome();__gs.newDoc(128,128,8,null,'Brush regression',false);});

const point=async(x,y)=>{const r=await p.locator('#stage').boundingBox(),q=await p.evaluate(([x,y])=>__gs.toScreen(x,y),[x,y]);return [r.x+q[0],r.y+q[1]];};
await p.mouse.move(...await point(64,64));await p.keyboard.down('Alt');ok(await p.evaluate(()=>document.querySelector('#brushCursor').hidden&&__gs.cvCanvas.style.cursor.includes('data:image/svg')), 'Alt shows an eyedropper and hides the brush outline');await p.keyboard.up('Alt');ok(await p.evaluate(()=>!document.querySelector('#brushCursor').hidden),'releasing Alt restores the brush cursor');
await p.keyboard.press('f');ok(await p.evaluate(()=>document.body.classList.contains('tabfull'))&&await p.locator('#stage').boundingBox().then(r=>r.width>1000),'F expands the canvas and hides panels');await p.keyboard.press('Escape');ok(await p.evaluate(()=>!document.body.classList.contains('tabfull')),'Escape restores the layout');await p.keyboard.press('f');await p.keyboard.press('f');ok(await p.evaluate(()=>!document.body.classList.contains('tabfull')),'F toggles back');
await p.evaluate(()=>__gs.setTool('liquify'));const bs=await p.evaluate(()=>__gs.brush.size),ls=await p.evaluate(()=>__gs.liq.size);await p.keyboard.press(']');ok(await p.evaluate(([bs,ls])=>__gs.liq.size>ls&&__gs.brush.size===bs,[bs,ls]),'brackets change Liquify size without changing paint size');const larger=await p.evaluate(()=>__gs.liq.size);await p.keyboard.press('[');ok(await p.evaluate(n=>__gs.liq.size<n,larger),'left bracket shrinks Liquify');ok(await p.locator('#ob_lqSize').inputValue()===String(await p.evaluate(()=>__gs.liq.size)),'bracket sizing synchronizes Liquify slider');
const twirls=await p.evaluate(async()=>{const G=__gs,results=[];for(const mode of ['cw','ccw']){G.newDoc(128,128,8,null,'Twirl',false);G.run(G.program('void main(){float c=length(gl_FragCoord.xy-vec2(83.0,64.0))<3.0?1.0:0.0;o=vec4(0,0,0,c);}'),G.doc.active.target,{});G.liq.mode=mode;G.liq.size=100;G.liq.strength=.8;G.liqDown({pointerId:42},64,64);for(let i=0;i<24;i++)G.liqDab(64,64,0,0,1);G.liqFlush();G.liqUp();const a=G.readRGBA8(G.doc.active.target);let n=0,y=0;for(let j=0;j<128;j++)for(let x=0;x<128;x++){const v=a[(j*128+x)*4+3];n+=v;y+=j*v;}results.push(y/n);await G.undo();const b=G.readRGBA8(G.doc.active.target);results.push(b[(64*128+83)*4+3]>240); }return results;});console.log('Twirl centres',twirls);ok(twirls[0]<60&&twirls[2]>68&&twirls[1]&&twirls[3],'both twirls deform in opposite directions and undo correctly');
const restoration=await p.evaluate(async()=>{const G=__gs;G.newDoc(128,128,8,[1,1,1],'Restore',false);G.run(G.program('void main(){float c=abs(gl_FragCoord.x-64.0)<2.0?0.0:1.0;o=vec4(vec3(c),1.0);}'),G.doc.active.target,{});const original=Array.from(G.readRGBA8(G.doc.active.target));G.liq.mode='push';G.liq.size=100;G.liq.strength=.8;G.liqDown({pointerId:42},64,64);G.liqDab(64,64,18,0,1);G.liqFlush();G.liqUp();const pushed=Array.from(G.readRGBA8(G.doc.active.target));G.liq.mode='restore';G.liqDown({pointerId:43},64,64);for(let i=0;i<60;i++)G.liqDab(64,64,0,0,1);G.liqFlush();G.liqUp();const restored=G.readRGBA8(G.doc.active.target),err=a=>{let n=0;for(let y=42;y<86;y++)for(let x=45;x<85;x++)n+=Math.abs(a[(y*128+x)*4]-original[(y*128+x)*4]);return n;},r={before:err(pushed),after:err(restored)};await G.undo();const undone=G.readRGBA8(G.doc.active.target);r.undo=pushed.every((v,i)=>v===undone[i]);return r;});console.log('Restore',restoration);ok(restoration.after<restoration.before*.2&&restoration.undo,'Restore paints back a previous deformation and is itself undoable');
const pools=[];for(const pressure of [.2,.85]){const r=await p.evaluate(async pressure=>{const G=__gs;G.newDoc(128,128,8,null,'Ink bleed',false);G.setTool('brush');G.applyPreset(G.library.find(s=>s.id==='bp_basic').presets.find(p=>p.name==='Gasa Gaya Pen'));const L=G.doc.active,o={...G.brush,tool:'brush',size:44,color:[0,0,0],sel:false};G.beginStroke(L,64,64,pressure,o);G.composite();const area=()=>{G.composite();return Array.from(G.readRGBA8(G.compOut())).filter((v,i)=>i%4===3&&v>100).length;};const initial=area();await new Promise(r=>setTimeout(r,900));const wet=area();G.endStroke(true);const final=area();await new Promise(r=>setTimeout(r,100));const stopped=area();await G.undo();const blank=area()===0;return {initial,wet,final,stopped,blank};},pressure);pools.push(r);}console.log('Pressure pools',pools);ok(pools.every(r=>r.wet>r.initial&&r.final===r.stopped&&r.blank),'ink spreads while held, stops at lift and undoes in one step');ok(pools[1].wet>pools[0].wet*2,'higher pressure produces a larger ink pool');
const dab=await p.evaluate(()=>{const G=__gs;G.newDoc(128,128,8,null,'Quick dab',false);const o={...G.brush,tool:'brush',size:44,color:[0,0,0],sel:false};G.beginStroke(G.doc.active,64,64,1,o);G.composite();const before=G.readRGBA8(G.compOut());G.endStroke(true);G.composite();const after=G.readRGBA8(G.compOut());return before.every((v,i)=>v===after[i]);});ok(dab,'quick dabs receive no extra bead at lift');
await p.evaluate(()=>{__gs.setTool('liquify');__gs.liq.mode='restore';});const stale=await p.evaluate(()=>{const G=__gs,n=G.hist.undo.length;G.liqDown({pointerId:44},64,64);G.liqUp();return G.hist.undo.length===n;});ok(stale,'Restore does not overwrite unrelated newer brush edits');
await p.evaluate(()=>{__gs.act('new');});await p.getByRole('button',{name:'Custom colour',exact:true}).click();await p.locator('#dBgHex').fill('');await p.locator('#dBgHex').focus();await p.keyboard.press('f');ok(await p.locator('#dBgHex').inputValue().then(v=>v==='f')&&!await p.evaluate(()=>document.body.classList.contains('tabfull')),'F remains normal input inside document fields');await p.locator('#dlgCancel').click();
ok(!errors.length,'no app errors');if(errors.length)console.log(errors);await b.close();server.closeAllConnections();await new Promise(r=>server.close(r));process.exit(fails?1:0);
})().catch(e=>{console.error(e);process.exit(1);});

