const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),http=require('http');
const root=path.resolve(__dirname,'../../dist'),out=path.resolve(__dirname,'out/favorites0513');fs.mkdirSync(out,{recursive:true});let fails=0;
const ok=(v,m)=>{console.log((v?'PASS ':'FAIL ')+m);if(!v)fails++;};
(async()=>{
const server=http.createServer((req,res)=>{const f=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!f.startsWith(root+path.sep)||!fs.existsSync(f)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',f.endsWith('.html')?'text/html':'application/octet-stream');fs.createReadStream(f).pipe(res);});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;
const native=process.env.GS_NATIVE_CDP,b=native?await chromium.connectOverCDP(native):await chromium.launch({channel:'msedge',headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']}),p=native?b.contexts()[0].pages()[0]:await b.newPage({viewport:{width:1500,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));await p.route('**/*',r=>r.request().url().startsWith(url)?r.continue():r.abort());await p.goto(url+'/index.html?debug');await p.waitForFunction(()=>window.__gs);await p.evaluate(()=>{__gs.closeWelcome();__gs.newDoc(128,128,8,null,'Brush regression',false);});


const drag=async(from,to)=>{await from.scrollIntoViewIfNeeded();const a=await from.boundingBox(),b=await to.boundingBox();const clip=await to.locator('xpath=ancestor::*[contains(@class,"dkfloat")]').boundingBox().catch(()=>null);if(clip)b.height=Math.min(b.height,clip.y+clip.height-12-b.y);await p.mouse.move(a.x+a.width/2,a.y+a.height/2);await p.mouse.down();await p.mouse.move(b.x+b.width/2,b.y+b.height/2,{steps:15});await p.mouse.up();await p.waitForTimeout(100);};
await p.evaluate(()=>{localStorage.removeItem('gs.favorites');__gs.favoritesState.lists={paint:[],p3d:[]};__gs.setMode('paint',true);__gs.setTool('brush');__gs.showPanel('brushes');__gs.showPanel('favorites');__gs.dkMove('favorites',{float:{x:180,y:220}});});
await drag(p.locator('#libBody button[aria-label="Gasa Pen"]').last(),p.locator('#favoritesBody'));ok(await p.locator('#favoritesBody button[aria-label="Gasa Pen"]').count()===1,'brush drag adds a favorite');const n=await p.evaluate(()=>__gs.hist.undo.length);await drag(p.locator('#libBody button[aria-label="Gasa Pen"]').last(),p.locator('#favoritesBody'));ok(await p.locator('#favoritesBody button[aria-label="Gasa Pen"]').count()===1&&await p.evaluate(n=>__gs.hist.undo.length===n,n),'duplicate drops do not add copies or paint layers');
await p.locator('#favoritesBody button[aria-label="Gasa Pen"]').click();ok(await p.evaluate(()=>__gs.brush.tip.name.includes('Gasa')),'favorite brush applies the preset');
await p.evaluate(()=>{const G=__gs;G.applyPreset(G.library[0].presets[0]);G.brush.size=73;G.applyPreset(G.library.find(s=>s.id==='bp_basic').presets.find(p=>p.name==='Gasa Pen'));G.brush.size=19;});await p.keyboard.press('Shift+b');ok(await p.evaluate(()=>__gs.brush.size===73),'Shift+B switches to the previous brush and its remembered size');await p.keyboard.press('Shift+b');ok(await p.evaluate(()=>__gs.brush.size===19),'Shift+B toggles back to the other brush');
await drag(p.locator('#tools .tool[data-tool="marquee"]'),p.locator('#favoritesBody'));ok(await p.locator('#favoritesBody .favorite-tile').filter({hasText:'Marquee'}).count()===1,'toolbar tool drag adds a favorite');await p.locator('#favoritesBody .favorite-tile').filter({hasText:'Marquee'}).click();ok(await p.evaluate(()=>__gs.ui.tool==='marquee'),'favorite tool activates it');await p.keyboard.press('b');
await p.evaluate(()=>__gs.showPanel('textures'));await p.waitForTimeout(100);await drag(p.locator('#tx_gen_clouds'),p.locator('#favoritesBody'));ok(await p.locator('#favoritesBody button[aria-label="Clouds"]').count()===1,'texture drag adds a favorite');await p.getByRole('searchbox',{name:'Search Favorites'}).fill('gasa');ok(await p.locator('#favoritesBody .favorite-tile').count()===1,'Favorites search filters items');await p.getByRole('searchbox',{name:'Search Favorites'}).fill('');
await p.getByLabel('Favorite type',{exact:true}).selectOption('tex');ok(await p.locator('#favoritesBody .favorite-tile').count()===1,'type filter separates brushes and textures');await p.getByLabel('Favorite type',{exact:true}).selectOption('all');await p.screenshot({path:path.join(out,'favorites-2d.png')});
await p.evaluate(()=>__gs.dkMove('favorites',{newGroup:0}));ok(await p.locator('.dkfloat #favoritesSec').count()===0&&await p.locator('.dkgrp #favoritesSec').count()===1,'Favorites docks back into the panel groups');await p.evaluate(()=>__gs.dkMove('favorites',{float:{x:180,y:220}}));const old=await p.locator('.dkfloat').filter({has:p.locator('#favoritesSec')}).boundingBox();const head=p.locator('.dkfloat').filter({has:p.locator('#favoritesSec')}).locator('.dktabs');const hr=await head.boundingBox();await p.mouse.move(hr.x+hr.width/2,hr.y+hr.height/2);await p.mouse.down();await p.mouse.move(hr.x+hr.width/2+60,hr.y+hr.height/2+50,{steps:12});await p.mouse.up();const moved=await p.locator('.dkfloat').filter({has:p.locator('#favoritesSec')}).boundingBox();ok(moved.x>old.x+40&&moved.y>old.y+30,'floating Favorites window can be dragged');

// Real pointer drops in the 2D canvas, layer stack, folder and mask.
await p.evaluate(()=>{__gs.dkMove('favorites',{icons:true});__gs.newDoc(128,128,8,null,'Texture drops',false);__gs.showPanel('layers');__gs.showPanel('textures');});
const dropAt=async(loc,x,y)=>{await loc.scrollIntoViewIfNeeded();const r=await loc.boundingBox();await p.mouse.move(r.x+r.width/2,r.y+r.height/2);await p.mouse.down();await p.mouse.move(x,y,{steps:15});await p.mouse.up();await p.waitForTimeout(250);};
let canvas=await p.locator('#stage').boundingBox();const before=await p.evaluate(()=>__gs.allLayers().length);
await dropAt(p.locator('#tx_gen_clouds'),canvas.x+canvas.width*.6,canvas.y+canvas.height*.5);
ok(await p.evaluate(n=>__gs.allLayers().length===n+1&&__gs.doc.active.name==='Clouds',before),'texture dropped on the 2D canvas creates a layer');
ok(await p.evaluate(()=>{const d=__gs.readRGBA8(__gs.mapT(__gs.doc.active,'base'));return d.some((v,i)=>i%4===3&&v>0);}), 'texture layer contains actual pixels');
await p.evaluate(()=>__gs.showPanel('layers'));let row=await p.locator('#layerList .lrow').first().boundingBox();
await dropAt(p.locator('#tx_gen_clouds'),row.x+row.width*.75,row.y+row.height*.45);
ok(await p.evaluate(n=>__gs.allLayers().length===n+2&&!__gs.doc.active.mask,before),'texture on an ordinary 2D layer row adds a layer instead of a mask');
await p.evaluate(()=>__gs.act('group'));await p.waitForTimeout(100);row=await p.locator('#layerList .lrow').first().boundingBox();
await dropAt(p.locator('#tx_gen_clouds'),row.x+row.width*.75,row.y+row.height*.5);
ok(await p.evaluate(()=>__gs.doc.active.parent.type==='group'&&__gs.doc.active.parent.children.length===2),'texture drops into a 2D layer folder');
await p.evaluate(()=>{__gs.cmdAddMask();__gs.showPanel('layers');__gs.dkMove('layers',{float:{x:720,y:180}});});await p.locator('#layerList .mthumb').first().scrollIntoViewIfNeeded();const target=await p.locator('#layerList .mthumb').first().boundingBox();
await dropAt(p.locator('#tx_gen_clouds'),target.x+target.width/2,target.y+target.height/2);
ok(await p.evaluate(()=>!!__gs.ui.msSel&&__gs.msRowOf(__gs.ui.msSel).kind==='image'),'texture on the mask thumbnail adds an editable picture row');
ok(await p.locator('#matEdBody').isVisible(),'mask Properties is available in 2D');
const maskRow=await p.evaluate(()=>__gs.ui.msSel.id);await p.evaluate(()=>__gs.undo());ok(await p.evaluate(id=>!__gs.doc.active.mask?.stack?.some(r=>r.id===id),maskRow),'mask picture drop can be undone');await p.evaluate(()=>__gs.redo());
await p.evaluate(()=>{__gs.vxSet(Math.PI/6,false);});ok(await p.locator('.compass-angle').innerText()==='30°','compass shows the current view rotation');await p.locator('.compass-angle').click();ok(await p.evaluate(()=>__gs.view.rot===0),'compass angle button straightens the view');
const dial=await p.locator('.compass-dial').boundingBox();await p.mouse.move(dial.x+dial.width/2,dial.y+8);await p.mouse.down();await p.mouse.move(dial.x+dial.width-8,dial.y+dial.height/2,{steps:12});await p.mouse.up();ok(await p.evaluate(()=>Math.abs(__gs.view.rot-Math.PI/2)<.05),'dragging the compass rotates the canvas freely');await p.screenshot({path:path.join(out,'canvas-compass.png')});await p.locator('.compass-dial').dblclick();ok(await p.evaluate(()=>__gs.view.rot===0),'double-click compass resets rotation');

await p.evaluate(()=>{__gs.setMode('p3d',true);__gs.showPanel('favorites');__gs.dkMove('favorites',{float:{x:180,y:220}});__gs.showPanel('brushes');});ok(!(await p.locator('#canvasCompass').isVisible()),'canvas compass is hidden in 3D Paint');ok(await p.locator('#favoritesBody .favorite-tile').count()===0&&await p.locator('#favoritesContext').innerText()==='3D Paint favorites','3D Paint starts with its separate Favorites collection');await drag(p.locator('#libBody button[aria-label="Round"]').last(),p.locator('#favoritesBody'));ok(await p.locator('#favoritesBody button[aria-label="Round"]').count()===1,'3D favorite brush is added independently');await p.evaluate(()=>__gs.showPanel('mats'));await p.waitForTimeout(150);const material=p.locator('#matBody .mattile').filter({hasText:'Plastic'}).first();await drag(material,p.locator('#favoritesBody'));ok(await p.locator('#favoritesBody .favorite-tile').count()===2,'material drag adds a 3D favorite');await p.screenshot({path:path.join(out,'favorites-3d.png')});
await p.evaluate(()=>{__gs.setMode('paint',true);__gs.showPanel('favorites');});ok(await p.locator('#favoritesBody .favorite-tile').count()===3&&await p.locator('#favoritesBody button[aria-label="Gasa Pen"]').count()===1,'returning to 2D restores only its collection');await p.locator('#favoritesBody button[aria-label="Remove Clouds from Favorites"]').click();ok(await p.locator('#favoritesBody .favorite-tile').count()===2,'removing a favorite removes only its reference');const saved=await p.evaluate(()=>JSON.parse(localStorage.getItem('gs.favorites')));ok(saved.paint.length===2&&saved.p3d.length===2&&!JSON.stringify(saved).includes('data:image'),'both collections persist small references');await p.reload();await p.waitForFunction(()=>window.__gs);await p.evaluate(()=>{__gs.closeWelcome();__gs.showPanel('favorites');});ok(await p.locator('#favoritesBody button[aria-label="Gasa Pen"]').count()===1,'favorites survive app reload');
await p.evaluate(()=>{__gs.setMode('paint',true);__gs.dlgWhatsNew();});ok(await p.locator('#dlgBody').innerText().then(s=>s.includes('0.51.3')&&s.includes('Favorites')&&s.includes('compass')),'official changes are embedded in What\'s new');await p.keyboard.press('Escape');
await p.evaluate(()=>{__gs.setTool('bucket');__gs.showPanel('favorites');__gs.dkMove('favorites',{float:{x:180,y:220}});});await drag(p.locator('#tools .tool[data-tool="bucket"]'),p.locator('#favoritesBody'));await p.evaluate(()=>__gs.setTool('brush'));await p.locator('#favoritesBody .favorite-tile').filter({hasText:'Paint bucket'}).click();ok(await p.evaluate(()=>__gs.ui.tool==='bucket'),'grouped tool variant favorites remain usable');
const healArrow=p.locator('#tools .tool[data-tool="heal"] .tool-arrow');await healArrow.click();ok(await p.locator('#menuPop [data-tool-choice="heal:source"]').isVisible(),'grouped tool arrows still open their related tool menu');await p.keyboard.press('Escape');
ok(!errors.length,'no app errors');if(errors.length)console.log(errors);await b.close();server.closeAllConnections();await new Promise(r=>server.close(r));process.exit(fails?1:0);
})().catch(e=>{console.error(e);process.exit(1);});
