const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),http=require('http');
const root=path.resolve(__dirname,'../../dist');let fails=0;const ok=(v,m)=>{console.log((v?'PASS ':'FAIL ')+m);if(!v)fails++;};
(async()=>{const server=http.createServer((req,res)=>{const f=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!f.startsWith(root+path.sep)||!fs.existsSync(f)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',f.endsWith('.html')?'text/html':'application/octet-stream');fs.createReadStream(f).pipe(res);});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;
 const b=await chromium.launch({channel:'msedge',headless:true,args:['--use-gl=angle','--use-angle='+ (process.env.GS_HARDWARE?'d3d11':'swiftshader'),'--enable-unsafe-swiftshader']}),p=await b.newPage({viewport:{width:1200,height:850}}),errors=[];p.setDefaultTimeout(60000);p.on('pageerror',e=>errors.push(e.stack));await p.addInitScript(()=>{localStorage.setItem('gs.p3d',JSON.stringify({size:128,layout:'3d'}));localStorage.setItem('gs.welcome','no');});await p.route('**/*',r=>r.request().url().startsWith(url)?r.continue():r.abort());await p.goto(url+'/index.html?debug');await p.waitForFunction(()=>window.__gs);await p.evaluate(()=>{__gs.closeWelcome();__gs.setMode('p3d');__gs.v3s().detail=0;__gs.v3s().uvs=1;});
 const gradient=await p.evaluate(()=>{const g=__gs,S=g.doc.w,src=g.makeTarget(S,S,8,false),dst=g.makeTarget(S,S,8,false),px=new Uint8Array(S*S*4);for(let y=0;y<S;y++)for(let x=0;x<S;x++)px.set([Math.round(255*(x+.5)/S),Math.round(255*(y+.5)/S),0,255],(y*S+x)*4);g.writeRegion(src,0,0,S,S,px);
  const results=[];for(const divisions of [1,16,32,64]){const lines=[];for(let y=0;y<=divisions;y++)for(let x=0;x<=divisions;x++)lines.push(`v ${x/divisions*2-1} ${y/divisions*2-1} 0`,`vt ${x/divisions} ${y/divisions}`);for(let y=0;y<divisions;y++)for(let x=0;x<divisions;x++){const a=y*(divisions+1)+x+1,c=a+1,d=a+divisions+1,e=d+1;lines.push(`f ${a}/${a} ${c}/${c} ${e}/${e}`,`f ${a}/${a} ${e}/${e} ${d}/${d}`);}g.useModel(g.parseOBJ(lines.join('\n')));g.meshConnectedBlur(src,dst,6,6,false);const out=g.captureRegionNow(dst,0,0,S,S).data;let max=0,total=0,count=0;for(let y=20;y<S-20;y++)for(let x=20;x<S-20;x++)for(let k=0;k<2;k++){const i=(y*S+x)*4+k,delta=Math.abs(out[i]-px[i]);max=Math.max(max,delta);total+=delta;count++;}results.push({divisions,max,mean:total/count});}g.disposeTarget(src);g.disposeTarget(dst);return {results,error:g.gl.getError()};});console.log('Gradient',gradient);ok(gradient.results.every(r=>r.max<=2&&r.mean<.05),'blur preserves a linear gradient independently of mesh triangulation');
 const stroke=await p.evaluate(async()=>{const g=__gs,m=g.parseOBJ('v -1 -1 0\nv 0 -1 0\nv 0 1 0\nv -1 1 0\nv 1 -1 .8\nv 1 1 .8\nvt .05 .1\nvt .4 .1\nvt .4 .9\nvt .05 .9\nvt .95 .1\nvt .6 .1\nvt .6 .9\nvt .95 .9\nvn 0 0 1\nvn -.62 0 .78\nf 1/1/1 2/2/1 3/3/1\nf 1/1/1 3/3/1 4/4/1\nf 2/5/2 5/6/2 6/7/2\nf 2/5/2 6/7/2 3/8/2');g.useModel(m);g.setTool('brush');g.setFG([1,0,0]);g.v3s().disp=0;Object.assign(g.v3.cam,{yaw:0,pitch:0,dist:3,tx:0,ty:0,tz:0});g.cmdAddLayer();const L=g.doc.active,o=g.paintOpts(g.editTarget()),sp=g.meshSpace(256,256);Object.assign(o,{space:sp,size:28,cageRs:1,pSize:false,pOpacity:false,smoothing:0,tip:null,hardness:1,flow:1,opacity:1,spacing:.1,extras:[]});g.beginStroke(L,95,128,1,o);g.addPoint(160,128,1);g.endStroke(true);const read=x=>g.captureRegionNow(L.target,x,64,1,1).data[3],left=read(50),right=read(120),gap=read(64),saved=Array.from(g.readRGBA8(L.target));await g.undo();const undo=g.readRGBA8(L.target).every((v,i)=>i%4!==3||v===0);await g.redo();const redo=g.readRGBA8(L.target).every((v,i)=>v===saved[i]);return {left,right,gap,undo,redo,error:g.gl.getError()};});console.log('Projected seam stroke',stroke);ok(stroke.left>245&&stroke.right>245&&stroke.gap===0&&stroke.undo&&stroke.redo,'projected stroke crosses mirrored UV islands and a hard-normal join with exact undo and redo');
 const curved=await p.evaluate(()=>{const g=__gs,S=g.doc.w,src=g.makeTarget(S,S,8,false),dst=g.makeTarget(S,S,8,false),px=new Uint8Array(S*S*4);for(let y=0;y<S;y++)for(let x=0;x<S;x++){const u=(x+.5)/S,v=(y+.5)/S;if(v<.1||v>.9||!(u>=.05&&u<=.4||u>=.6&&u<=.95))continue;px.set(u<.5?[255,0,0,255]:[0,0,255,255],(y*S+x)*4);}g.writeRegion(src,0,0,S,S,px);const read=x=>Array.from(g.captureRegionNow(dst,x,64,1,1).data);const used=g.meshConnectedBlur(src,dst,6,6,false),left=read(50),right=read(121);g.meshConnectedBlur(src,dst,12,12,true);const boxLeft=read(50),boxRight=read(121);g.disposeTarget(src);g.disposeTarget(dst);return {used,left,right,boxLeft,boxRight,error:g.gl.getError()};});console.log('Folded mirrored seam blur',curved);ok(curved.used&&curved.left[2]>30&&curved.right[0]>30&&curved.left[3]>245&&curved.right[3]>245&&curved.boxLeft[2]>30&&curved.boxRight[0]>30,'Gaussian and box blur follow a folded surface across mirrored islands without reading transparent gutters');
 ok(errors.length===0&&gradient.error===0&&stroke.error===0&&curved.error===0,'no application or WebGL errors');await b.close();await new Promise(r=>server.close(r));process.exit(fails?1:0);
})().catch(e=>{console.error(e);process.exit(1);});

