/* 0.23: mask stacks (rows under a layer: paint, fill, noise, generators, filters) and content effects. */
const {chromium}=require('playwright');
const OLD=__dirname+'/';
const OUT=__dirname+'/out/';
let fails=0;const ok=(c,m)=>{console.log((c?'PASS ':'FAIL ')+m);if(!c)fails++;};
(async()=>{
 const b=await chromium.launch({args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const ctx=await b.newContext({viewport:{width:1440,height:1000}});const p=await ctx.newPage();
 await p.route('**/*',r=>{const u=r.request().url();
  if(u.includes('pako'))return r.fulfill({path:OLD+'node_modules/pako/dist/pako.min.js',contentType:'text/javascript'});
  if(u.includes('UTIF.js'))return r.fulfill({path:OLD+'node_modules/utif/UTIF.js',contentType:'text/javascript'});
  if(u.includes('ag-psd'))return r.fulfill({path:OLD+'node_modules/ag-psd/dist/bundle.js',contentType:'text/javascript'});
  if(u.startsWith('file:'))return r.continue();return r.abort();});
 const errs=[];p.on('pageerror',e=>errs.push('PAGEERR '+e.stack));p.on('console',m=>{if(m.type()==='error'&&!m.text().includes('ERR_'))errs.push(m.text());if(m.type()==='warning'&&/GL|WebGL/.test(m.text()))errs.push('GLWARN '+m.text());});
 await p.goto('file://'+require('path').resolve(__dirname,'../../dist-web/index.html')+'?debug');await p.waitForTimeout(2500);
 const W=ms=>p.waitForTimeout(ms||150);
 await p.evaluate(()=>__gs.newDoc(64,64,8,[1,1,1],'mode31',false));await p.waitForTimeout(400);
 await p.evaluate(()=>__gs.act('addLayer'));await p.waitForTimeout(200);
 await p.evaluate(()=>{__gs.msAdd(__gs.doc.active,'fill',{p:{v:1}});__gs.msAdd(__gs.doc.active,'noise',{p:{type:'clouds',scale:4,contrast:3,level:0,seed:3,tri:false,inv:false}});});await p.waitForTimeout(500);
 const n=await p.locator('#layerList .msrow.m button.msmode').count();ok(n===2,'each mask row has a blend button ('+n+')');
 const first=p.locator('#layerList .msrow.m button.msmode').first();
 const before=await first.textContent();
 await first.click();await p.waitForTimeout(200);
 ok(await p.locator('#menuPop .mi[role=menuitemradio]').count()>=3,'clicking the blend name opens the list');
 await p.click('#menuPop .mi:has-text("Multiply")');await p.waitForTimeout(400);
 const modes=await p.evaluate(()=>__gs.doc.active.mask.stack.map(r=>r.mode||'normal'));
 ok(modes.includes('multiply'),'blend mode changed on the row ('+before+' -> '+modes.join(',')+')');
 ok(await p.locator('#layerList .msrow.m button.msmode:text("Mult")').count()===1,'row label shows the new mode');
 await p.evaluate(()=>__gs.act('undo'));await p.waitForTimeout(300);
 ok(!(await p.evaluate(()=>__gs.doc.active.mask.stack.map(r=>r.mode||'normal'))).includes('multiply'),'undo puts it back');
 ok(errs.length===0,'no errors '+errs.join('|').slice(0,200));
 console.log(fails?fails+' FAILED':'ALL PASSED');await b.close();process.exit(fails?1:0);
})();
