const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),http=require('http');
const root=path.resolve(__dirname,'../../dist'),out=path.resolve(__dirname,'out/paint051');let fails=0;
fs.mkdirSync(out,{recursive:true});
const ok=(v,m)=>{console.log((v?'PASS ':'FAIL ')+m);if(!v)fails++;};
(async()=>{
const server=http.createServer((req,res)=>{const f=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!f.startsWith(root+path.sep)||!fs.existsSync(f)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',f.endsWith('.html')?'text/html':'application/octet-stream');fs.createReadStream(f).pipe(res);});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;
const native=process.env.GS_NATIVE_CDP,b=native?await chromium.connectOverCDP(native):await chromium.launch({channel:'msedge',headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']}),p=native?b.contexts()[0].pages()[0]:await b.newPage({viewport:{width:1500,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));await p.route('**/*',r=>r.request().url().startsWith(url)?r.continue():r.abort());await p.goto(url+'/index.html?debug');await p.waitForFunction(()=>window.__gs);await p.evaluate(()=>__gs.closeWelcome());
const mip=await p.evaluate(()=>{const G=__gs,g=G.gl,t=G.makeTarget(1024,1024,8,false),ref=G.makeTarget(1024,1024,8,false);G.clearTarget(t,[1,1,1,1]);g.bindTexture(g.TEXTURE_2D,t.tex);g.generateMipmap(g.TEXTURE_2D);const rs=[[71,109,210,390],[710,210,160,500],[180,670,130,61]];
const shader=G.program('void main(){vec2 p=gl_FragCoord.xy;float a=mod(floor(p.x/4.0)+floor(p.y/4.0),2.0);o=vec4(.1,.2,.3,a);}');for(const r of rs)G.scissorDo(r,()=>G.run(shader,t,{}));G.blit(t,ref,0,0,1024,1024,0,0);g.bindTexture(g.TEXTURE_2D,ref.tex);g.generateMipmap(g.TEXTURE_2D);for(const r of rs)G.v3PatchMips(t,r);let max=0,W=1024,H=1024;const diffs=[];for(let level=0;level<=10;level++){const read=v=>{g.bindFramebuffer(g.FRAMEBUFFER,v.fbo);g.framebufferTexture2D(g.FRAMEBUFFER,g.COLOR_ATTACHMENT0,g.TEXTURE_2D,v.tex,level);const a=new Uint8Array(W*H*4);g.readPixels(0,0,W,H,g.RGBA,g.UNSIGNED_BYTE,a);return a;};const a=read(t),b=read(ref);let d=0;for(let i=0;i<a.length;i++)d=Math.max(d,Math.abs(a[i]-b[i]));diffs.push(d);max=Math.max(max,d);W=Math.max(1,W>>1);H=Math.max(1,H>>1);}g.bindFramebuffer(g.FRAMEBUFFER,null);G.disposeTarget(t);G.disposeTarget(ref);return {max,diffs,error:g.getError()};});console.log('RGBA mip parity',mip);ok(mip.max<=2&&mip.error===0,'regional colour/alpha mips match full regeneration without damaging base pixels');
const pen=await p.evaluate(()=>{const G=__gs;G.newDoc(900,440,8,null,'Gasa Gaya Pen sample',false);G.setTool('brush');const preset=G.library.find(s=>s.id==='bp_basic').presets.find(p=>p.name==='Gasa Gaya Pen');if(!preset)return {found:false};G.applyPreset(preset);const L=G.doc.active;G.clearTarget(L.target,[1,1,1,1]);const o={...G.brush,size:36,color:[0,0,0],sel:false};
const line=(points,opt=o)=>{G.beginStroke(L,...points[0],opt);for(const p of points.slice(1))G.addPoint(...p);G.endStroke(true);};
line(Array.from({length:351},(_,i)=>[40+i*2,80,.03+.97*Math.pow(Math.sin(i/350*Math.PI),1.5)]));
const width=x=>{const a=G.captureRegionNow(L.target,x,40,1,80).data;let n=0;for(let i=0;i<a.length;i+=4)if(a[i]<64&&a[i+3]===255)n++;return n;},thin=width(60),thick=width(390),center=G.captureRegionNow(L.target,390,80,1,1).data;
line(Array.from({length:341},(_,i)=>[40+i*2,170+Math.sin(i/340*Math.PI*2)*36,.07+.93*Math.pow(Math.sin(i/340*Math.PI),.7)]));
// Angular contours, solid marker areas and fine hatching use the same preset.
line([[50,295,.08],[105,245,.7],[125,285,.5],[170,240,.8],[195,296,.08]],{...o,size:16});
for(let i=0;i<13;i++)line([[260+i*5,315,.5],[300+i*5,250,.5]],{...o,size:4});
for(let y=250;y<320;y+=5)line([[440,y,1],[570,y,1]],{...o,size:12});
G.composite();G.drawView();const a=G.captureRegionNow(L.target,0,0,900,440).data,c=document.createElement('canvas');c.width=900;c.height=440;const ctx=c.getContext('2d');ctx.putImageData(new ImageData(new Uint8ClampedArray(a),900,440),0,0);ctx.fillStyle='#222';ctx.font='20px sans-serif';ctx.fillText('Gasa Gaya Pen — pressure taper, contours, hatching and solid ink',30,395);
return {found:true,thin,thick,center:Array.from(center),pressure:G.brush.pSize,steady:!G.brush.pOpacity,png:c.toDataURL().split(',')[1]};});
if(pen.png)fs.writeFileSync(path.join(out,'gasa-gaya-pen.png'),Buffer.from(pen.png,'base64'));delete pen.png;console.log('Gasa Gaya Pen',pen);ok(pen.found&&pen.pressure&&pen.steady&&pen.thick>=25&&pen.thin<pen.thick/3&&pen.center?.join(',')==='0,0,0,255','library pen has a fine pressure taper and opaque black core');
for(const size of native?[8192,16384]:[1024]){
const r=await p.evaluate(size=>{const G=__gs,g=G.gl;G.newDoc(size,size,8,null,'High resolution regression',false);G.setTool('brush');const L=G.doc.active;G.clearTarget(L.target,[1,1,1,1]);G.composite();G.drawView();const o={...G.brush,tool:'brush',size:70,hardness:1,pSize:false,pOpacity:false,grain:0,opacity:1,flow:1,color:[0,0,0],sel:false};G.beginStroke(L,size*.2,size*.3,1,o);G.addPoint(size*.3,size*.4,1);G.composite();G.drawView();G.addPoint(size*.4,size*.3,1);G.composite();G.drawView();const t=G.compOut(),read=()=>G.captureRegionNow(t,Math.floor(size*.7),Math.floor(size*.7),8,8).data;const before=read(),base=G.captureRegionNow(t,Math.floor(size*.3)-4,Math.floor(size*.4)-4,8,8).data;
// Read the image actually shown at reduced zoom, then regenerate the same image fully.
const pix=()=>{G.drawView();g.bindFramebuffer(g.FRAMEBUFFER,null);const a=new Uint8Array(G.cvCanvas.width*G.cvCanvas.height*4);g.readPixels(0,0,G.cvCanvas.width,G.cvCanvas.height,g.RGBA,g.UNSIGNED_BYTE,a);return a;};const during=pix();g.bindTexture(g.TEXTURE_2D,t.tex);g.generateMipmap(g.TEXTURE_2D);const full=pix();let difference=0;for(let i=0;i<full.length;i++)difference=Math.max(difference,Math.abs(full[i]-during[i]));G.endStroke(true);G.composite();const saved=G.captureRegionNow(L.target,Math.floor(size*.3)-4,Math.floor(size*.4)-4,8,8).data;return {difference,white:before.every(v=>v===255),black:Array.from(base).every((v,i)=>i%4===3?v===255:v===0),savedBlack:Array.from(saved).every((v,i)=>i%4===3?v===255:v===0),error:g.getError()};},size);console.log('Painting',size,r);ok(r.difference<=2&&r.white&&r.black&&r.savedBlack&&r.error===0,size+'px brush preview and saved pixels remain intact');}
await p.screenshot({path:path.join(out,'painting-desktop.png')});ok(!errors.length,'no application errors');if(errors.length)console.log(errors);await b.close();await new Promise(r=>server.close(r));process.exit(fails?1:0);
})().catch(e=>{console.error(e);process.exit(1);});
