const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),http=require('http');
const root=path.resolve(__dirname,'../../dist'),out=path.resolve(__dirname,'out/paint0514');fs.mkdirSync(out,{recursive:true});let fails=0;
const ok=(v,m)=>{console.log((v?'PASS ':'FAIL ')+m);if(!v)fails++;};
(async()=>{
const server=http.createServer((req,res)=>{const f=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!f.startsWith(root+path.sep)||!fs.existsSync(f)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',f.endsWith('.html')?'text/html':'application/octet-stream');fs.createReadStream(f).pipe(res);});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;
const native=process.env.GS_NATIVE_CDP,b=native?await chromium.connectOverCDP(native):await chromium.launch({channel:'msedge',headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']}),p=native?b.contexts()[0].pages()[0]:await b.newPage({viewport:{width:1500,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));await p.route('**/*',r=>r.request().url().startsWith(url)?r.continue():r.abort());await p.addInitScript(()=>localStorage.setItem('gs.favorites',JSON.stringify({paint:[{kind:'brush',set:'bp_basic',name:'Gasa Gaya Pen'}],p3d:[]})));await p.goto(url+'/index.html?debug');await p.waitForFunction(()=>window.__gs);await p.evaluate(()=>{__gs.closeWelcome();__gs.newDoc(128,128,8,null,'Brush regression',false);});

const point=async(x,y)=>{const r=await p.locator('#stage').boundingBox(),q=await p.evaluate(([x,y])=>__gs.toScreen(x,y),[x,y]);return [r.x+q[0],r.y+q[1]];};
ok(await p.evaluate(()=>{const r=__gs.favoritesState.lists.paint[0];return r.name==='Gasa Pen'&&__gs.favoritesResolve(r)?.name==='Gasa Pen';}),'existing Gasa favorites migrate to the new name');
await p.evaluate(()=>{const G=__gs;G.setMode('paint',true);G.newDoc(512,512,8,[1,1,1],'Rotated text',false);G.ui.textStyle.size=32;G.setTool('text');G.vxSet(Math.PI/4,false);});await p.mouse.click(...await point(130,220));await p.locator('textarea.texted').fill('Canvas\norientation');await p.waitForTimeout(100);
ok(await p.evaluate(()=>Math.abs(__gs.view.rot-Math.PI/4)<1e-6),'adding and typing text preserves the rotated canvas');
const editorCheck=()=>{const G=__gs,L=G.doc.active,b=L.text.bbox,A=[Math.cos(G.view.rot)*(G.view.flip?-1:1),-Math.sin(G.view.rot),Math.sin(G.view.rot)*(G.view.flip?-1:1),Math.cos(G.view.rot)],e=document.querySelector('.texted'),m=new DOMMatrix(e.style.transform),q=G.toScreen(b.bx,b.by);return Math.abs(parseFloat(e.style.left)-q[0])<.05&&Math.abs(parseFloat(e.style.top)-q[1])<.05&&Math.abs(m.a-A[0])<1e-5&&Math.abs(m.b-A[2])<1e-5&&Math.abs(m.c-A[1])<1e-5&&Math.abs(m.d-A[3])<1e-5;};
ok(await p.evaluate(editorCheck),'text editor origin and orientation match the rendered canvas');await p.screenshot({path:path.join(out,'rotated-text.png')});await p.evaluate(()=>__gs.vxSet(-Math.PI/6,true));await p.waitForTimeout(100);ok(await p.evaluate(editorCheck),'editing follows rotation and mirror changes without straightening');await p.keyboard.press('Escape');const textBefore=await p.evaluate(()=>__gs.doc.active.text.content);await p.evaluate(()=>__gs.undo());ok(await p.evaluate(()=>!__gs.allLayers().some(L=>L.text)),'rotated text creation undoes normally');await p.evaluate(()=>__gs.redo());ok(await p.evaluate(c=>__gs.doc.active.text.content===c,textBefore),'rotated text creation redoes normally');
await p.evaluate(()=>{__gs.vxSet(.25,false);__gs.setTool('text');});const centre=await p.evaluate(()=>{const b=__gs.doc.active.text.bbox;return [b.bx+b.bw/2,b.by+b.bh/2];});await p.mouse.click(...await point(...centre));ok(await p.locator('textarea.texted').isVisible()&&await p.evaluate(()=>Math.abs(__gs.view.rot-.25)<1e-6),'reopening existing text keeps the canvas angle');await p.keyboard.press('Escape');
// Thin strips exercise full 8K/16K coordinates without allocating a whole multi-gigabyte document.
for(const size of [8192,16384])for(const vertical of [false,true]){const r=await p.evaluate(({size,vertical})=>{const G=__gs,w=vertical?128:size,h=vertical?size:128,t=G.makeTarget(w,h,8,false),def=G.gradDef([{p:0,c:[.4,.4,.4]},{p:1,c:[.6,.6,.6]}],null,{method:'classic'}),g={def,a:[0,0],b:vertical?[0,size]:[size,0]};G.drawGradient(t,g);G.gl.bindFramebuffer(G.gl.FRAMEBUFFER,t.fbo);const d=new Uint8Array(w*h*4);G.gl.readPixels(0,0,w,h,G.gl.RGBA,G.gl.UNSIGNED_BYTE,d);let mixed=0,maxError=0;for(let j=1;j<80;j++){const pos=Math.floor(size*j/80),vals=[];for(let k=0;k<128;k++)vals.push(d[((vertical?pos:k)*w+(vertical?k:pos))*4]);if(new Set(vals).size>1)mixed++;maxError=Math.max(maxError,Math.abs(vals.reduce((a,b)=>a+b,0)/128/255-(.4+.2*(pos+.5)/size)));}G.release(t);return {mixed,maxError};},{size,vertical});console.log('Dither',size,vertical,r);ok(r.mixed>65&&r.maxError<.001,size+' '+(vertical?'vertical':'horizontal')+' gradient dithers without biased bands');}
const precision=await p.evaluate(()=>{const G=__gs,w=16384,src=G.makeTarget(w,1,32,false),dst=G.makeTarget(w,1,32,false),def=G.gradDef([{p:0,c:[.4,.4,.4]},{p:1,c:[.42,.42,.42]}],null,{method:'classic',dither:false}),get=t=>{G.gl.bindFramebuffer(G.gl.FRAMEBUFFER,t.fbo);const d=new Float32Array(w*4);G.gl.readPixels(0,0,w,1,G.gl.RGBA,G.gl.FLOAT,d);return d;};G.drawGradient(src,{def,a:[0,0],b:[w,0]});G.gl.bindTexture(G.gl.TEXTURE_2D,src.tex);G.gl.texParameteri(G.gl.TEXTURE_2D,G.gl.TEXTURE_MIN_FILTER,G.gl.NEAREST);G.gl.texParameteri(G.gl.TEXTURE_2D,G.gl.TEXTURE_MAG_FILTER,G.gl.NEAREST);let a=get(src),unique=new Set(),error=0;for(let x=0;x<w;x++){unique.add(a[x*4]);error=Math.max(error,Math.abs(a[x*4]-(.4+.02*(x+.5)/w)));}G.FX.gradMap.render(src,dst,{def:G.gradDef([{p:0,c:[0,0,0]},{p:1,c:[1,1,1]}],null,{method:'classic',dither:false}),rev:false});const b=get(dst);let mapError=0;for(let x=0;x<w;x++)mapError=Math.max(mapError,Math.abs(b[x*4]-a[x*4]));G.release(src);G.release(dst);return {unique:unique.size,error,mapError,glError:G.gl.getError()};});console.log('Gradient precision',precision);ok(precision.unique>16000&&precision.error<1e-6,'16K narrow gradient retains precision without lookup plateaus');ok(precision.mapError<1e-6&&precision.glError===0,'Gradient map interpolates the float lookup strip instead of sampling steps');
const alpha=await p.evaluate(()=>{const G=__gs,t=G.makeTarget(4096,16,8,false),def=G.gradDef([{p:0,c:[.7,.2,.1]},{p:1,c:[.7,.2,.1]}],[{p:0,a:0},{p:1,a:1}],{method:'classic'});G.drawGradient(t,{def,a:[64,0],b:[4032,0]},{opacity:.3});G.gl.bindFramebuffer(G.gl.FRAMEBUFFER,t.fbo);const a=new Uint8Array(4096*16*4);G.gl.readPixels(0,0,4096,16,G.gl.RGBA,G.gl.UNSIGNED_BYTE,a);let valid=true;for(let i=0;i<a.length;i+=4)if(a[i]>a[i+3]||a[i+1]>a[i+3]||a[i+2]>a[i+3])valid=false;const ends=a[3]===0&&Math.abs(a[(4095*4)+3]/255-.3)<1/255;G.release(t);return {valid,ends};});ok(alpha.valid&&alpha.ends,'transparent low-opacity gradients stay premultiplied and preserve their endpoints');
await p.evaluate(()=>{const G=__gs;G.vxSet(0,false);G.newDoc(512,128,8,null,'Live gradient',false);G.setTool('gradient');G.ui.grad=G.gradDef([{p:0,c:[.25,.25,.25]},{p:1,c:[.65,.65,.65]}],null,{method:'classic'});G.ui.gradLive=true;});await p.mouse.move(...await point(10,64));await p.mouse.down();await p.mouse.move(...await point(502,64),{steps:12});await p.mouse.up();ok(await p.evaluate(()=>!!__gs.doc.active.grad&&__gs.doc.active.grad.def.dither),'real gradient drag creates a live dithered gradient');await p.evaluate(()=>__gs.undo());ok(await p.evaluate(()=>!__gs.allLayers().some(L=>L.grad)),'live gradient creation remains undoable');await p.evaluate(()=>__gs.redo());ok(await p.evaluate(()=>__gs.allLayers().some(L=>L.grad)),'live gradient redoes normally');
const display=await p.evaluate(()=>{const G=__gs;G.newDoc(256,256,16,[.401,.401,.401],'Display precision',false);G.composite();G.drawView();const t=G.cvCanvas,d=new Uint8Array(128*128*4);G.gl.bindFramebuffer(G.gl.FRAMEBUFFER,null);G.gl.readPixels(Math.round(t.width/2)-64,Math.round(t.height/2)-64,128,128,G.gl.RGBA,G.gl.UNSIGNED_BYTE,d);const levels=new Set();for(let i=0;i<d.length;i+=4)levels.add(d[i]);return [...levels];});console.log('Display levels',display);ok(display.length===2&&Math.max(...display)-Math.min(...display)===1,'16-bit canvas display dithers between adjacent levels without altering texture storage');
const pens=await p.evaluate(async()=>{const G=__gs,list=G.library.find(s=>s.id==='bp_basic').presets,pens=list.filter(p=>['Gasa Pen','Gasa Manga Pen'].includes(p.name)),results=[];G.newDoc(600,360,8,null,'Gasa brushes',false);G.setTool('brush');for(let i=0;i<pens.length;i++){const p=pens[i];G.applyPreset(p);const y=85+i*150,o={...G.brush,tool:'brush',size:32,color:[0,0,0],sel:false};G.beginStroke(G.doc.active,60,y,.05,o);for(let k=1;k<=300;k++){const t=k/300;G.addPoint(60+470*t,y+Math.sin(t*Math.PI*2)*12,.05+.95*Math.sin(Math.PI*t));}G.endStroke(true);G.composite();const a=G.readRGBA8(G.mapT(G.doc.active,'base'));let width=0;for(let yy=y-45;yy<y+45;yy++)if(a[(yy*600+295)*4+3]>128)width++;G.beginStroke(G.doc.active,560,y,1,o);G.composite();const area=()=>{G.composite();return Array.from(G.readRGBA8(G.compOut())).filter((v,j)=>j%4===3&&v>80).length;},initial=area();await new Promise(r=>setTimeout(r,700));const wet=area();G.endStroke(true);results.push({name:p.name,width,initial,wet,tip:p.tip.name,size:p.size});}G.composite();const a=G.readRGBA8(G.compOut()),c=document.createElement('canvas');c.width=600;c.height=360;const temp=document.createElement('canvas');temp.width=600;temp.height=360;temp.getContext('2d').putImageData(new ImageData(new Uint8ClampedArray(a),600,360),0,0);const x=c.getContext('2d');x.fillStyle='white';x.fillRect(0,0,600,360);x.drawImage(temp,0,0);x.fillStyle='#333';x.font='18px sans-serif';x.fillText('Gasa Pen',40,40);x.fillText('Gasa Manga Pen',40,190);return {results,png:c.toDataURL().split(',')[1]};});fs.writeFileSync(path.join(out,'gasa-brushes.png'),Buffer.from(pens.png,'base64'));console.log('Pens',pens.results);ok(pens.results.length===2&&pens.results[1].width<pens.results[0].width*.6,'Manga pen is substantially narrower at the same brush size');ok(pens.results.every(r=>r.wet>r.initial),'both Gasa versions retain slight ink bleed');ok(pens.results[0].size===9&&pens.results[1].size===7,'current Gasa preset is retained alongside the smaller manga version');
await p.evaluate(()=>__gs.dlgWhatsNew());ok(await p.locator('#dlgBody').innerText().then(s=>s.includes('0.51.4')&&s.includes('Gasa Manga Pen')&&s.includes('Rotated text')),'release changes are embedded in What\'s new');await p.keyboard.press('Escape');ok(!errors.length,'no app errors');if(errors.length)console.log(errors);await b.close();server.closeAllConnections();await new Promise(r=>server.close(r));process.exit(fails?1:0);
})().catch(e=>{console.error(e);process.exit(1);});
