/* Native desktop visual checks on the user's material mesh and supplied maps. */
const {chromium}=require('playwright'),fs=require('fs'),path=require('path');
(async()=>{const b=await chromium.connectOverCDP(process.env.GS_NATIVE_CDP),p=b.contexts()[0].pages()[0],origin=new URL(p.url()).origin,root=path.resolve(__dirname,'../../dist'),out=path.resolve(__dirname,'out/studio-update');p.setDefaultTimeout(120000);
 await p.route('**/*',r=>{const u=r.request().url();if(u.startsWith(origin)){const f=path.resolve(root,'.'+decodeURIComponent(new URL(u).pathname));if(f.startsWith(root+path.sep)&&fs.existsSync(f))return r.fulfill({path:f});}return r.abort();});
 await p.evaluate(async()=>{const G=__gs;G.p3.savedAt=G.p3Sig();await G.p3NewProject(1024);await G.studioPreviewMaps();G.studioLightingPreset('soft');Object.assign(G.v3s(),{floor:true,floorOpacity:.3,floorSoft:4});G.changedAll();});await p.waitForTimeout(1000);
 const shot=async name=>{const img=await p.evaluate(()=>{const G=__gs,W=800,H=800,px=G.v3Offscreen(W,H),c=document.createElement('canvas');c.width=W;c.height=H;const x=c.getContext('2d'),d=x.createImageData(W,H);for(let y=0;y<H;y++)d.data.set(px.subarray((H-1-y)*W*4,(H-y)*W*4),y*W*4);x.putImageData(d,0,0);return c.toDataURL();});fs.writeFileSync(path.join(out,name+'.png'),Buffer.from(img.split(',')[1],'base64'));};
 await shot('material-preview');const smart=await p.evaluate(async()=>{const G=__gs,rec=G.smBuiltins().find(m=>m.name==='Workshop · Worn painted metal'),group=await G.smApply(rec);return !!group&&group.children.some(l=>l.mask?.stack?.some(r=>r.kind==='gen'));});if(!smart)throw Error('Map-driven smart material failed');await p.waitForTimeout(1000);await shot('smart-material-preview');
 const masked=await p.evaluate(async()=>{const G=__gs,L=G.allLayers().find(l=>l.name==='Exposed steel at chipped edges');G.selectOnly(L);await G.smMaskApply(G.smaskBuiltins().find(m=>m.name==='Workshop · Armour edge highlights'));G.changedAll();return !!L.mask?.stack?.some(r=>r.kind==='gen');});if(!masked)throw Error('Smart mask failed');await p.waitForTimeout(1000);await shot('smart-mask-preview');
 const info=await p.evaluate(()=>{const G=__gs,e=G.gl.getExtension('WEBGL_debug_renderer_info');return {bridge:G.platform.isDesktop,renderer:G.gl.getParameter(e.UNMASKED_RENDERER_WEBGL),resolution:G.doc.w,maps:Object.keys(G.doc.meshMaps),error:G.gl.getError()};});console.log(JSON.stringify(info));if(!info.bridge||/software|swiftshader/i.test(info.renderer)||info.error)throw Error('Native graphics validation failed');console.log('PASS native material and smart-mask previews');await b.close();
})().catch(e=>{console.error(e);process.exit(1);});
