/* Editable Bézier paths. Each path owns a layer: a compact fill recipe and one coverage
   mask, rather than a full-size painted image for every material channel. */
const pathEdit={L:null,point:-1,drawing:false,drag:null};
let pathPanelFor=null;
const pathMeshCaches=new WeakMap();
function pathCopy(p){return JSON.parse(JSON.stringify(p));}
function pathActive(){const L=doc.active;return L?.path&&inDoc(L)?L:null;}
function pathToolOn(){return (ui.tool==='pen'&&['paint','p3d'].includes(ui.mode))||(ui.tool==='path'&&ui.mode==='p3d');}
function pathMeshIndex(m){let C=pathMeshCaches.get(m);if(C)return C;const n=m.idx.length/3,ids=Uint32Array.from({length:n},(_,i)=>i),bounds=new Float32Array(n*6);let hash=2166136261;
  for(let t=0;t<n;t++){const b=t*6;bounds[b]=bounds[b+1]=bounds[b+2]=Infinity;bounds[b+3]=bounds[b+4]=bounds[b+5]=-Infinity;
    for(let k=0;k<3;k++){const v=m.idx[t*3+k]*3;hash=Math.imul(hash^m.idx[t*3+k],16777619);for(let j=0;j<3;j++){const x=m.pos[v+j];bounds[b+j]=Math.min(bounds[b+j],x);bounds[b+3+j]=Math.max(bounds[b+3+j],x);hash=Math.imul(hash^(Math.round(x*1e6)|0),16777619);}}}
  const build=(a,b)=>{const lo=[Infinity,Infinity,Infinity],hi=[-Infinity,-Infinity,-Infinity];for(let i=a;i<b;i++){const q=ids[i]*6;for(let j=0;j<3;j++){lo[j]=Math.min(lo[j],bounds[q+j]);hi[j]=Math.max(hi[j],bounds[q+3+j]);}}
    const N={lo,hi,a,b};if(b-a<=16)return N;let ax=0;for(let j=1;j<3;j++)if(hi[j]-lo[j]>hi[ax]-lo[ax])ax=j;const mid=(lo[ax]+hi[ax])*2;let i=a,j=b-1;
    while(i<=j){const q=ids[i]*6;if(bounds[q+ax]+bounds[q+3+ax]<mid/2)i++;else{const v=ids[i];ids[i]=ids[j];ids[j--]=v;}}
    if(i===a||i===b)i=(a+b)>>1;N.l=build(a,i);N.r=build(i,b);return N;};
  C={ids,bounds,tree:build(0,n),sig:[m.pos.length,m.idx.length,hash>>>0].join(':')};pathMeshCaches.set(m,C);return C;}
/* Closest point on a triangle (barycentric region tests), including its interpolated normal. */
function pathTriPoint(m,t,p){const ids=[0,1,2].map(i=>m.idx[t*3+i]),A=ids.map(i=>Array.from(m.pos.subarray(i*3,i*3+3))),ab=sub3(A[1],A[0]),ac=sub3(A[2],A[0]),ap=sub3(p,A[0]);
  const d1=dot3(ab,ap),d2=dot3(ac,ap);let u=0,v=0;
  if(!(d1<=0&&d2<=0)){const bp=sub3(p,A[1]),d3=dot3(ab,bp),d4=dot3(ac,bp);
    if(d3>=0&&d4<=d3)u=1;else{const vc=d1*d4-d3*d2;if(vc<=0&&d1>=0&&d3<=0)u=d1/(d1-d3);else{const cp=sub3(p,A[2]),d5=dot3(ab,cp),d6=dot3(ac,cp);
      if(d6>=0&&d5<=d6)v=1;else{const vb=d5*d2-d1*d6;if(vb<=0&&d2>=0&&d6<=0)v=d2/(d2-d6);else{const va=d3*d6-d5*d4;if(va<=0&&d4-d3>=0&&d5-d6>=0){v=(d4-d3)/((d4-d3)+(d5-d6));u=1-v;}else{const z=1/(va+vb+vc);u=vb*z;v=vc*z;}}}}}}
  const q=A[0].map((x,i)=>x+ab[i]*u+ac[i]*v),w=[1-u-v,u,v],normal=[0,0,0];for(let i=0;i<3;i++)for(let k=0;k<3;k++)normal[k]+=(m.nrm?m.nrm[ids[i]*3+k]:sel3Nrm(m,t)[k])*w[i];
  return {p:q,n:norm3(normal),tri:t,d:dot3(sub3(q,p),sub3(q,p))};}
function pathNearest(m,p,range){const C=pathMeshIndex(m),R=range||p3Range(),distance=N=>N.lo.reduce((s,x,i)=>s+Math.pow(Math.max(x-p[i],0,p[i]-N.hi[i]),2),0);let best=null;
  const visit=N=>{if(best&&distance(N)>best.d)return;if(N.l){let a=N.l,b=N.r;if(distance(a)>distance(b))[a,b]=[b,a];visit(a);visit(b);}else for(let i=N.a;i<N.b;i++){const t=C.ids[i];if(t<R.start||t>=R.start+R.count)continue;const q=pathTriPoint(m,t,p);if(!best||q.d<best.d)best=q;}};visit(C.tree);return best;}
function pathCurve(a,b,t){const h=a.out||a.p.map(()=>0),j=b.in||b.p.map(()=>0),s=1-t;return a.p.map((x,i)=>s*s*s*x+3*s*s*t*(x+h[i])+3*s*t*t*(b.p[i]+j[i])+t*t*t*b.p[i]);}
function pathSamples(P,surface){const out=[],pts=P.points,n=pts.length;if(n<2)return out;const count=n-1+(P.closed?1:0),radius=P.width/2;
  for(let i=0;i<count;i++){const a=pts[i],b=pts[(i+1)%n],length=Math.hypot(...sub3d(b.p,a.p))+Math.hypot(...(a.out||[]))+Math.hypot(...(b.in||[])),steps=clamp(Math.ceil(length/Math.max(surface?radius*.4:.8,.0001)),4,256);
    for(let j=0;j<=steps;j++){if(i&&j===0)continue;const t=j/steps,p=pathCurve(a,b,t),q=surface?pathNearest(v3.mesh,p):{p};if(!q)continue;out.push({p:q.p,n:q.n,pressure:(a.pressure??1)*(1-t)+(b.pressure??1)*t,segment:i,t});}}
  return out;}
function sub3d(a,b){return a.map((v,i)=>v-b[i]);}
function pathValid(L){return L.path.kind!=='3d'||!!(v3.mesh&&v3.gpu&&!v3.mesh.noUV&&pathMeshIndex(v3.mesh).sig===L.path.mesh);}
function pathNew(kind){const L=newLayerObj(kind==='3d'?'Surface path':'Pen path',true),P={kind,points:[],closed:false,mode:kind==='3d'?'stroke':'none',width:kind==='3d'?(v3.mesh?.radius||1)*.035:brush.size,hardness:brush.hardness,opacity:brush.opacity,spacing:brush.spacing,angle:brush.angle||0,roundness:brush.roundness||1,pressure:true};
  if(kind==='3d')P.mesh=pathMeshIndex(v3.mesh).sig;L.path=P;if(kind==='3d'&&brush.tip?.name==='Weld bead'&&typeof weldPathSetup==='function')weldPathSetup(L);else L.fill=fillDefaults();for(const k in L.fill.maps)L.fill.maps[k].on=false;L.fill.maps.base={on:true,src:'value',c:ui.fg.slice()};L.fill.coverH=false;L.fill.proj='uv';fillRender(L);
  L.mask=makeMask(0,true);L.editMask=false;const tip=brush.tip;if(tip?.tex){L._fillImg={pathTip:makeTarget(tip.w,tip.h,8,false)};blit(tip,L._fillImg.pathTip,0,0,tip.w,tip.h,0,0);P.tipName=tip.name;}
  structOp('New '+(kind==='3d'?'surface':'Pen')+' path',()=>{const [p,i]=insertPoint();insertNode(L,p,i);selectOnly(L);});pathEdit.L=L;pathEdit.point=-1;pathEdit.drawing=true;return L;}
function pathRecord(L,before,label){const after=pathCopy(L.path);if(JSON.stringify(before)===JSON.stringify(after))return;
  const put=p=>{L.path=pathCopy(p);selectOnly(L);pathEdit.L=L;pathEdit.point=-1;pathEdit.drawing=false;pathEdit.drag=null;delete L._pathPreview;pathRender(L);if(pathToolOn())buildBrushPanel();};pushUndo({label:label||'Edit path',refs:[L],undo(){put(before);},redo(){put(after);}});changed(L);}
function pathFlush(){for(const L of allLayers())if(L._pathBefore){clearTimeout(L._pathTimer);const b=L._pathBefore;L._pathBefore=null;pathRecord(L,b,'Path settings');}}
function pathChange(fn,label){pathFlush();const L=pathActive();if(!L||lockStop({node:L}))return;if(!pathValid(L)){toast('This path belongs to a different mesh. Its saved texture is preserved.');return;}const b=pathCopy(L.path);fn(L.path);pathRender(L);pathRecord(L,b,label);buildBrushPanel();}
function pathSplit(P,i,t=.5){const a=P.points[i],b=P.points[(i+1)%P.points.length];if(!a||!b||!P.closed&&i===P.points.length-1)return;
  const mix=(x,y)=>x.map((v,j)=>v*(1-t)+y[j]*t),c=a.p.map((v,j)=>v+(a.out?.[j]||0)),d=b.p.map((v,j)=>v+(b.in?.[j]||0)),A=mix(a.p,c),B=mix(c,d),C=mix(d,b.p),D=mix(A,B),E=mix(B,C),F=mix(D,E),q=P.kind==='3d'?pathNearest(v3.mesh,F):{p:F};
  a.out=sub3d(A,a.p);b.in=sub3d(C,b.p);P.points.splice(i+1,0,{p:q.p,n:q.n,pressure:(a.pressure||1)*(1-t)+(b.pressure||1)*t,in:sub3d(D,q.p),out:sub3d(E,q.p)});}
/* Surface ribbon coverage is evaluated in world space while rasterizing the mesh into UVs.
   This crosses separate UV islands and does not depend on the current camera. */
const FS_SURFACEPATH=`in vec3 vP; in vec3 vN; uniform vec3 uA; uniform vec3 uB; uniform vec3 uNA; uniform vec3 uNB; uniform vec2 uRadius; uniform float uDepth; uniform float uHard; uniform sampler2D uTip; uniform int uUseTip; uniform float uAspect;
void main(){vec3 ab=uB-uA; float t=clamp(dot(vP-uA,ab)/max(dot(ab,ab),1e-10),0.0,1.0);vec3 n=normalize(mix(uNA,uNB,t)),q=vP-mix(uA,uB,t);float z=dot(q,n),r=mix(uRadius.x,uRadius.y,t);if(dot(normalize(vN),n)<0.15||abs(z)>uDepth){o=vec4(0.0);return;}vec3 tangent=ab-n*dot(ab,n);tangent=normalize(length(tangent)>1e-6?tangent:cross(n,abs(n.y)<0.9?vec3(0,1,0):vec3(1,0,0)));vec3 side=normalize(cross(n,tangent));vec2 xy=vec2(dot(q,tangent),dot(q,side))/max(r,1e-6);float d=length(xy),aa=max(fwidth(d),0.002),a=1.0-smoothstep(uHard,max(uHard+aa,1.0),d);if(uUseTip==1){vec2 uv=xy*vec2(0.5/max(uAspect,1.0),0.5*min(uAspect,1.0))+0.5;a=all(greaterThanEqual(uv,vec2(0)))&&all(lessThanEqual(uv,vec2(1)))?texture(uTip,uv).a:0.0;}o=vec4(a,a,a,a);}`;
let P_SURFACEPATH=null;
function pathSurfaceMask(L,samples){if(!P_SURFACEPATH)P_SURFACEPATH=prog3(VS_3DPROJ,FS_SURFACEPATH);const m=v3.mesh,g=v3.gpu,C=pathMeshIndex(m),R=p3Range(),V=gl.createVertexArray(),E=gl.createBuffer(),T=L.mask.target,P=L.path,r=P.width/2,tip=L._fillImg?.pathTip;
  gl.bindVertexArray(V);gl.bindBuffer(gl.ARRAY_BUFFER,g.vb);for(const [a,n,o] of [[0,3,0],[1,3,12],[2,2,24],[4,3,48]]){gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,n,gl.FLOAT,false,60,o);}gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,E);
  try{for(let i=1;i<samples.length;i++){const a=samples[i-1],b=samples[i],pad=r*1.2,lo=a.p.map((v,k)=>Math.min(v,b.p[k])-pad),hi=a.p.map((v,k)=>Math.max(v,b.p[k])+pad),tris=[],bb=[Infinity,Infinity,-Infinity,-Infinity];
      const overlaps=(l,h)=>l.every((v,k)=>v<=hi[k]&&h[k]>=lo[k]);const visit=N=>{if(!overlaps(N.lo,N.hi))return;if(N.l){visit(N.l);visit(N.r);}else for(let j=N.a;j<N.b;j++){const t=C.ids[j],q=t*6;if(t<R.start||t>=R.start+R.count||!overlaps(C.bounds.subarray(q,q+3),C.bounds.subarray(q+3,q+6)))continue;for(let k=0;k<3;k++){const v=m.idx[t*3+k];tris.push(v);bb[0]=Math.min(bb[0],m.uv[v*2]*doc.w);bb[1]=Math.min(bb[1],m.uv[v*2+1]*doc.h);bb[2]=Math.max(bb[2],m.uv[v*2]*doc.w);bb[3]=Math.max(bb[3],m.uv[v*2+1]*doc.h);}}};visit(C.tree);if(!tris.length)continue;
      gl.bindVertexArray(V);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,E);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint32Array(tris),gl.STREAM_DRAW);bindTarget(T);gl.disable(gl.DEPTH_TEST);gl.disable(gl.CULL_FACE);gl.enable(gl.SCISSOR_TEST);gl.scissor(Math.max(0,Math.floor(bb[0]-1)),Math.max(0,Math.floor(bb[1]-1)),Math.ceil(bb[2]-bb[0]+2),Math.ceil(bb[3]-bb[1]+2));gl.enable(gl.BLEND);gl.blendEquation(gl.MAX);gl.blendFunc(gl.ONE,gl.ONE);
      useProg(P_SURFACEPATH,{uUVs:1,uShift:[0,0],uH:dummy,uDisp:0,uUseH:false,uA:a.p,uB:b.p,uNA:a.n,uNB:b.n,uRadius:[r*(P.pressure?a.pressure:1),r*(P.pressure?b.pressure:1)],uDepth:pad,uHard:P.hardness,uTip:tip?.tex||dummy,uUseTip:!!tip,uAspect:tip?tip.w/tip.h:1});gl.drawElements(gl.TRIANGLES,tris.length,gl.UNSIGNED_INT,0);}}
  finally{gl.disable(gl.SCISSOR_TEST);gl.disable(gl.BLEND);gl.blendEquation(gl.FUNC_ADD);gl.bindVertexArray(vao);gl.deleteVertexArray(V);gl.deleteBuffer(E);}}
function pathRender(L){if(!L.path||!L.mask||!pathValid(L))return;const P=L.path,T=L.mask.target;clearTarget(T,[0,0,0,1]);if(P.points.length<2||P.mode==='none'){changed(L);return;}
  const s=P.kind==='3d'?L._pathSamples:pathSamples(P,false);if(P.kind==='3d')pathSurfaceMask(L,s);
  else if(P.mode==='fill'){if(!P.closed){changed(L);return;}rasterPoly(s.flatMap(a=>a.p),T,true);}
  else{useAux(T.depth);const o=Object.assign({},BRUSH_DEFAULTS,{tool:'brush',size:P.width,hardness:P.hardness,opacity:1,flow:1,spacing:P.spacing,pSize:P.pressure,minSize:.05,color:[1,1,1],noTint:true,angle:P.angle,roundness:P.roundness,tip:L._fillImg?.pathTip||null});
    beginStroke({target:T,maskOf:L,lockAlpha:false},s[0].p[0],s[0].p[1],s[0].pressure,o);for(let i=1;i<s.length;i++)addPoint(s[i].p[0],s[i].p[1],s[i].pressure);endStroke(false);}
  L.opacity=P.opacity;changed(L);}
function pathProject(p,kind,hit){if(kind==='2d')return toScreen(p[0],p[1]);const r=hit.getBoundingClientRect(),{VP}=v3ViewProj(r.width,r.height),w=VP[3]*p[0]+VP[7]*p[1]+VP[11]*p[2]+VP[15];if(w<=0)return null;return [((VP[0]*p[0]+VP[4]*p[1]+VP[8]*p[2]+VP[12])/w*.5+.5)*r.width,(.5-(VP[1]*p[0]+VP[5]*p[1]+VP[9]*p[2]+VP[13])/w*.5)*r.height];}
function pathOverlay(kind){const hit=kind==='3d'?document.getElementById('v3Hit'):stage;if(!hit)return;let c=hit.parentNode.querySelector('.path-overlay[data-kind="'+kind+'"]');if(!c){c=el('canvas',{class:'path-overlay','data-kind':kind,'aria-hidden':'true'});hit.parentNode.append(c);}c.hidden=!pathToolOn();if(c.hidden)return;
  const r=hit.getBoundingClientRect(),pr=hit.parentNode.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2),w=Math.round(r.width*d),h=Math.round(r.height*d);if(c.width!==w||c.height!==h){c.width=w;c.height=h;}c.style.left=(r.left-pr.left)+'px';c.style.top=(r.top-pr.top)+'px';c.style.width=r.width+'px';c.style.height=r.height+'px';const x=c.getContext('2d');x.setTransform(d,0,0,d,0,0);x.clearRect(0,0,r.width,r.height);
  for(const L of allLayers()){const P=L.path;if(!P||P.kind!==kind||!L.visible||!pathValid(L))continue;const active=L===doc.active,pts=P.points;x.strokeStyle=active?'#ffc763':'#6fd5ff';x.lineWidth=1.5;
    const samples=kind==='3d'?(L._pathPreview||L._pathSamples||(L._pathSamples=pathSamples(P,true))):pathSamples(P,false);x.beginPath();let start=true;for(const a of samples){const q=pathProject(a.p,kind,hit);if(!q){start=true;continue;}if(start)x.moveTo(...q);else x.lineTo(...q);start=false;}x.stroke();
    pts.forEach((p,i)=>{const q=pathProject(p.p,kind,hit);if(!q)return;if(active)for(const k of ['in','out']){if(!p[k]||Math.hypot(...p[k])<1e-6)continue;const v=pathProject(p.p.map((a,j)=>a+p[k][j]),kind,hit);if(!v)continue;x.beginPath();x.moveTo(...q);x.lineTo(...v);x.stroke();x.fillStyle='#202429';x.beginPath();x.arc(...v,3,0,Math.PI*2);x.fill();x.stroke();}x.fillStyle=active&&i===pathEdit.point?'#ffc763':'#202429';x.fillRect(q[0]-4,q[1]-4,8,8);x.strokeRect(q[0]-4,q[1]-4,8,8);});}}
function pathHit(hit,e,kind){const r=hit.getBoundingClientRect(),p=[e.clientX-r.left,e.clientY-r.top],layers=allLayers().filter(L=>L.path?.kind===kind&&L.visible&&pathValid(L)).reverse();
  for(const L of layers)for(let i=0;i<L.path.points.length;i++){const a=L.path.points[i],keys=L===doc.active?['in','out','anchor']:['anchor'];for(const k of keys){if(k!=='anchor'&&(!a[k]||Math.hypot(...a[k])<1e-6))continue;const q=pathProject(k==='anchor'?a.p:a.p.map((v,j)=>v+a[k][j]),kind,hit);if(q&&Math.hypot(q[0]-p[0],q[1]-p[1])<9)return {L,i,k};}}return null;}
function pathEventPoint(hit,e,kind){if(kind==='2d')return {p:toImage(e.clientX,e.clientY)};const pk=v3PickAt(hit,e);if(!pk||pk.set!==p3.cur)return null;return pathNearest(v3.mesh,pk.pos);}
function pathDown(hit,e,kind){if(!pathToolOn()||(kind==='2d'&&ui.tool!=='pen')||(kind==='3d'&&ui.tool!=='path')||e.button!==0||spaceDown||e.altKey&&!pathHit(hit,e,kind))return false;
  if(stroke||preview||xf||selLive||tabDocs.hold||gfSaving||bk.busy)return true;if(kind==='3d'&&(!v3.mesh||v3.mesh.noUV))return true;
  pathFlush();const found=pathHit(hit,e,kind),q=pathEventPoint(hit,e,kind);if(!q&&!found)return true;let L=found?.L||pathActive();if(!L||L.path.kind!==kind||!pathValid(L)||!pathEdit.drawing&&!found)L=pathNew(kind);
  if(lockStop({node:L})||lockedPos(L)){if(lockedPos(L))lockMsg(L,'position');return true;}selectOnly(L);const before=pathCopy(L.path);let index=found?.i,k=found?.k||'new';
  if(found&&index===0&&pathEdit.drawing&&L.path.points.length>=3&&!e.ctrlKey&&!e.altKey){L.path.closed=true;pathEdit.drawing=false;pathRender(L);pathRecord(L,before,'Close path');buildBrushPanel();return true;}
  if(!found){index=L.path.points.length;L.path.points.push({p:q.p,n:q.n,pressure:pressureOf(e),in:q.p.map(()=>0),out:q.p.map(()=>0)});}
  pathEdit.L=L;pathEdit.point=index;pathEdit.drag={id:e.pointerId,L,index,k,before,origin:pathCopy(L.path.points[index]),start:[e.clientX,e.clientY],hit,kind,moved:false};try{hit.setPointerCapture(e.pointerId);}catch(er){}renderLayers();buildBrushPanel();requestRender();return true;}
function pathMove(e){const D=pathEdit.drag;if(!D||D.id!==e.pointerId)return false;const q=pathEventPoint(D.hit,e,D.kind);if(!q)return true;D.moved=D.moved||Math.hypot(e.clientX-D.start[0],e.clientY-D.start[1])>2;const p=D.L.path.points[D.index];
  if(D.k==='anchor'){p.p=q.p;p.n=q.n;}else if(D.moved){const delta=sub3d(q.p,D.origin.p),key=D.k==='new'?'out':D.k;p[key]=delta;if(!e.altKey)p[key==='in'?'out':'in']=delta.map(v=>-v);}if(D.kind==='3d')D.L._pathPreview=pathSamples(D.L.path,true);requestRender();return true;}
function pathUp(e,cancel){const D=pathEdit.drag;if(!D||D.id!==e.pointerId)return false;pathEdit.drag=null;delete D.L._pathPreview;if(cancel)D.L.path=D.before;pathRender(D.L);if(!cancel)pathRecord(D.L,D.before,D.k==='new'?'Add path point':'Move path point');buildBrushPanel();return true;}
function pathFinish(){pathFlush();pathEdit.drawing=false;pathEdit.drag=null;buildBrushPanel();requestRender();}
function pathResize(fx,fy,ox,oy){for(const L of everyLayer())if(L.path?.kind==='2d'){for(const p of L.path.points){p.p=[p.p[0]*fx+ox,p.p[1]*fy+oy];for(const k of ['in','out'])if(p[k])p[k]=[p[k][0]*fx,p[k][1]*fy];}L.path.width*=(fx+fy)/2;pathRender(L);}if(pathToolOn())buildBrushPanel();}
function pathKeys(e){if(!pathToolOn()||e.defaultPrevented||e.ctrlKey||e.metaKey||e.altKey||!modal.hidden||openName||!pop.hidden||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)||e.target.isContentEditable)return false;
  const L=pathActive();if(e.key==='Enter'||e.key==='Escape'){if(pathEdit.drag)pathUp({pointerId:pathEdit.drag.id},e.key==='Escape');pathFinish();e.preventDefault();e.stopImmediatePropagation();return true;}
  if((e.key==='Delete'||e.key==='Backspace')&&L&&pathEdit.point>=0){const i=pathEdit.point;pathChange(P=>P.points.splice(i,1),'Delete path point');pathEdit.point=-1;e.preventDefault();e.stopImmediatePropagation();return true;}return false;}
function pathNewButton(){pathFinish();pathEdit.L=null;pathEdit.point=-1;selectOnly(null);pathEdit.drawing=true;buildBrushPanel();requestRender();}
function pathPanel(box){const L=pathActive(),P=L?.path;pathPanelFor=doc.active;$('#brushTitle').textContent=ui.tool==='path'?'Surface Path':'Pen';
  box.append(el('p',{class:'note',text:ui.tool==='path'?'Click on the model to add points. Drag a new point for a curve. Alt+drag rotates the model. Enter finishes; click a point to edit it.':'Click for corners; click and drag for Bézier handles. Drag points or handles to edit. Alt+drag a handle breaks its pair. Click the first point to close. Enter finishes.'}),
    el('div',{class:'chips'},el('button',{class:'btn sm',id:'pathNew',text:'New path',onclick:pathNewButton}),el('button',{class:'btn sm',id:'pathFinish',text:'Finish',disabled:!P,onclick:pathFinish})));
  if(!P){box.append(el('p',{class:'note',text:'Start a path on the '+(ui.tool==='path'?'model.':'canvas.')}));return;}
  const name=el('input',{id:'pathName',value:L.name,'aria-label':'Path name'});name.onchange=()=>{const b=L.name,a=name.value.trim()||b;L.name=a;pushUndo({label:'Rename path',refs:[L],undo(){L.name=b;},redo(){L.name=a;}});changed(L);};box.append(name,
    seg((P.kind==='3d'?[['stroke','Paint along path']]:[['none','Path only'],['stroke','Brush stroke'],['fill','Fill']]),P.mode,v=>pathChange(p=>{p.mode=v;if(v==='fill'&&p.points.length>=3)p.closed=true;},'Path painting mode'),'Path painting mode'),
    el('div',{class:'chips'},chk('pathClosed','Closed path',P.closed,v=>pathChange(p=>p.closed=v,'Close/open path')),chk('pathPressure','Point pressure',P.pressure,v=>pathChange(p=>p.pressure=v,'Path pressure'))));
  const sl=(id,label,key,min,max,step,fmt)=>makeSlider({id,label,min,max,step,value:P[key],fmt,onInput:v=>{if(lockStop({node:L}))return;const b=pathCopy(L.path);L.path[key]=v;pathRender(L);clearTimeout(L._pathTimer);if(!L._pathBefore)L._pathBefore=b;L._pathTimer=setTimeout(()=>{const old=L._pathBefore;L._pathBefore=null;pathRecord(L,old,'Path '+label.toLowerCase());},400);}}).el;
  box.append(sl('pathWidth','Width','width',P.kind==='3d'?.001:1,P.kind==='3d'?2:1000,P.kind==='3d'?.001:1,v=>P.kind==='3d'?v.toFixed(3)+' units':Math.round(v)+' px'),sl('pathHard','Hardness','hardness',0,1,.01,pct),sl('pathOpacity','Opacity','opacity',0,1,.01,pct));
  const point=P.points[pathEdit.point];if(point)box.append(makeSlider({id:'pathPointPressure',label:'Point pressure',min:.05,max:1,step:.01,value:point.pressure||1,fmt:pct,onInput:v=>{if(lockStop({node:L}))return;if(!L._pathBefore)L._pathBefore=pathCopy(L.path);point.pressure=v;requestRender();},onChange:()=>{pathRender(L);pathFlush();}}).el,
    el('div',{class:'chips'},el('button',{class:'btn sm',text:'Corner',onclick:()=>pathChange(p=>{const q=p.points[pathEdit.point];q.in=q.p.map(()=>0);q.out=q.p.map(()=>0);},'Corner point')}),el('button',{class:'btn sm',text:'Smooth',onclick:()=>pathChange(p=>{const i=pathEdit.point,q=p.points[i],a=p.points[(i-1+p.points.length)%p.points.length],b=p.points[(i+1)%p.points.length];q.out=sub3d(b.p,a.p).map(v=>v/6);q.in=q.out.map(v=>-v);},'Smooth point')}),el('button',{class:'btn sm',text:'Insert point after',onclick:()=>pathChange(p=>pathSplit(p,pathEdit.point),'Insert path point')}),el('button',{class:'btn sm',text:'Delete point',onclick:()=>{const i=pathEdit.point;pathChange(p=>p.points.splice(i,1),'Delete path point');pathEdit.point=-1;}})));
  box.append(colourBtn('pathColor',()=>L.fill.maps.base.c||ui.fg,c=>{if(lockStop({node:L}))return;matEdBegin(L);L.fill.maps.base={on:true,src:'value',c};fillRender(L);matEdCommit();},'Path colour'),
    el('button',{class:'btn sm',id:'pathMaterial',text:'Use selected library material',onclick:async()=>{if(matSel.kind!=='mat'){toast('Select a material in the Materials shelf.');showPanel('mats');return;}const r=matSel.rec;if(lockStop({node:L}))return;try{if(r.bundled)await gmLoad(r);const need=Object.keys(r.fill.maps).filter(k=>r.fill.maps[k].on&&MAP_DEFS[k]&&!doc.maps.includes(k)&&!(doc.workflow==='spec'&&(k==='rough'||k==='metal')));if(need.length)setDocMaps([...doc.maps,...need],'Path material channels');matEdBegin(L);L.fill=fillClone(r.fill);L.fill.coverH=false;L._fillImg=L._fillImg||{};for(const k in matRecTargets(r)){const t=r._t[k],copy=makeTarget(t.w,t.h,8,true);blit(t,copy,0,0,t.w,t.h,0,0);L._fillImg[k]=copy;}fillRender(L);matEdCommit();buildBrushPanel();}catch(e){toast('Could not load material: '+e.message);}}}),
    el('div',{class:'chips'},P.kind==='2d'?el('button',{class:'btn sm',id:'pathSelect',text:'Make selection',disabled:!P.closed||P.points.length<3,onclick:()=>selectPolygon(pathSamples(P,false).flatMap(a=>a.p),ui.selMode,'Path selection',true)}):null,el('button',{class:'btn sm',id:'pathDuplicate',text:'Duplicate path',onclick:cmdDuplicate}),el('button',{class:'btn sm',id:'pathDelete',text:'Delete path',onclick:cmdDelete})));
  box.append(el('div',{class:'sub',text:'Paths on this document'}),...allLayers().filter(n=>n.path?.kind===P.kind).map(n=>el('button',{class:'btn sm'+(n===L?' on':''),text:n.name,onclick:()=>{selectOnly(n);pathEdit.L=n;pathEdit.point=-1;pathEdit.drawing=false;changed(n);buildBrushPanel();}})));}
/* Capture path editing before ordinary painting/navigation, including rebuilt 3D panes. */
document.addEventListener('pointerdown',e=>{const hit=e.target.closest?.('#v3Hit')||(e.target===cv?stage:null);if(!hit)return;const kind=hit.id==='v3Hit'?'3d':'2d';if(pathDown(hit,e,kind)){e.preventDefault();e.stopImmediatePropagation();}},true);
window.addEventListener('pointermove',e=>{if(pathMove(e)){e.preventDefault();e.stopImmediatePropagation();}},true);
window.addEventListener('pointerup',e=>{if(pathUp(e,false)){e.preventDefault();e.stopImmediatePropagation();}},true);
window.addEventListener('pointercancel',e=>pathUp(e,true),true);window.addEventListener('blur',()=>{if(pathEdit.drag)pathUp({pointerId:pathEdit.drag.id},true);});window.addEventListener('keydown',e=>pathKeys(e),true);
{const dv=drawView;drawView=function(){dv();pathOverlay('2d');};const d3=draw3D;draw3D=function(){d3();pathOverlay('3d');};const pr=pathRender;pathRender=function(L){if(L.path.kind==='3d'&&pathValid(L))L._pathSamples=pathSamples(L.path,true);pr(L);};}
(function(){for(const [tool,label,icon] of [['material','Material brush','<path d="m5 17 9-9 3 3-9 9H5z"/><path d="M3 3h6v6H3zM15 3h6v4h-6z"/>'],['pen','Pen','<path d="m4 20 3-11 6-6 8 8-6 6zM7 9l8 8M4 20l7-7"/><circle cx="12" cy="12" r="1.5"/>'],['path','Surface Path','<path d="M4 17c0-12 16 12 16-10"/><rect x="2" y="15" width="4" height="4"/><rect x="18" y="5" width="4" height="4"/>']]){const b=el('button',{class:'tool','data-tool':tool,title:label,'aria-label':label,'aria-pressed':'false'});b.innerHTML='<svg viewBox="0 0 24 24">'+icon+'</svg>';b.onclick=()=>setTool(tool);$('#tools').insertBefore(b,$('#tools .tool[data-tool="text"]'));}})();
