/* ================= Boot ================= */
renderLibrary();buildBrushPanel();applyPreset(PRESETS[0]);loadSavedSets();loadSavedFonts();refreshChanUI();
setFG(ui.fg);renderRecent();resizeGL();
dkInit();syncWsSel();setTimeout(dkReopenPops,500);{const s=$('#wsSel');s.onchange=()=>{const v=s.value;if(v===':save')saveWorkspaceAs();else if(v===':reset')resetWorkspace();else if(v===':delete')deleteWorkspace();else if(v)setWorkspace(v);syncWsSel();};}if(dk.lock)document.body.classList.add('dklock');
try{buildSample();toast('Sample tile loaded. Paint on it, or start fresh from File › New document.');}catch(err){console.error(err);newDoc(1024,1024,8,[1,1,1],'Untitled',false);}
updateStatus();requestRender(true);
refreshMapsUI();
if(platform.isDesktop){setTimeout(()=>checkForUpdates(false),4000);platform.launchFile().then(p=>{if(p)openPath(p,'open');});}
/* test hook: only with ?debug in the address */
if(/[?&]debug\b/.test(location.search))window.__gs={doc,sel,view,hist,ui,readRGBA8,selPixels:()=>captureSel(sel.t,[0,0,doc.w,doc.h]).data,inPaint:f=>withPaintDoc(f),get tabDocs(){return tabDocs;},layerByName:n=>allLayers().find(L=>L.name===n),newDoc,get xf(){return xf;},get crop(){return crop;},xfHandles:()=>xf&&!xf.warp?xfHandles():null,toScreen,encodePSD,openPSD,setMode,get anim(){return doc.anim;},get mode(){return ui.mode;},get onionT(){return onionT;},get playing(){return playing;},setView,setEditMap,setDocMaps,mapT,compositeMap,release,clearTarget,mapKeysOf,paintLayers,compOut:()=>compOut,brush,buildTextures,TEX_PRESETS,texCfg,encodeGouache,openGouache,allLayers,dlgConvert,get sel(){return sel;},act:k=>actions[k](),bakeCfg,parseOBJ,bakeRun,bakeViewModel,runBake,primMeshX:k=>primMesh(k,0),undo:()=>undo(),redo:()=>redo(),dlgFill:()=>dlgFillLayer(),prefs,useModel:m=>{v3.imported=m;v3s().model="imported";v3LoadModel();},get p3(){return p3;},mir3,mir3Mats,st3,st3Use,st3Builtin,st3Load,sel3,v3PickAt,encodeP3Project,openP3Project,p3SwitchSet,cagePt,cageInv,cageChanged,bk,bakeSend,bakeRegion,bakeMapT,meshSpace,v3,primMesh,cv:cvS,cvSourceFromDoc,cvSourceFromFile,library,showPanel,setWorkspace,dk,wfSwitch,wfAsk,cvSetKind,cvSend,cvOpen,cvRes,loadStart,loadSet,loadEnd,cageFwd,cageMesh,toggleCageFlat,setTool,symCopies,get bvhVia(){return bvhBuildAsync.via;}};
